const KEY='onpoint.ops.stable.v2';
const pages=[['dashboard','Dashboard'],['daily','Daily Entry'],['importer','Reliable Import'],['costs','Cost Ledger'],['pnl','P&L Bridge'],['reconcile','Reconcile'],['forecast','Forecast'],['people','People'],['actions','Actions'],['dataqa','Data QA'],['settings','Settings']];
const today=()=>new Date().toISOString().slice(0,10);
const n=x=>Number(String(x??'').replace(/[$,]/g,'').replace(/[()]/g,m=>m==='('?'-':''))||0;
const money=x=>(n(x)<0?'-$':'$')+Math.abs(Math.round(n(x))).toLocaleString();
const num=x=>Math.round(n(x)).toLocaleString();
const pct=x=>isFinite(x)?Number(x).toFixed(1)+'%':'0.0%';
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let current='dashboard',previewRows=[];
function rules(){return[['mckesson','COGS / Inventory','Inventory','McKesson','Pharmacy Ops'],['cardinal','COGS / Inventory','Inventory','Cardinal','Pharmacy Ops'],['cencora','COGS / Inventory','Inventory','Cencora','Pharmacy Ops'],['amerisource','COGS / Inventory','Inventory','Cencora','Pharmacy Ops'],['adp','Labor','Payroll','Payroll','Pharmacy Ops'],['payroll','Labor','Payroll','Payroll','Pharmacy Ops'],['rent','Rent','Location','Unassigned Location','Pharmacy Ops'],['uber','Delivery','Workflow','Delivery','Pharmacy Ops'],['doordash','Delivery','Workflow','Delivery','Pharmacy Ops'],['usps','Delivery','Workflow','Delivery','Pharmacy Ops'],['openai','Technology','Software','AI / Tech','Technology'],['google','Technology','Software','Google','Technology'],['microsoft','Technology','Software','Microsoft','Technology'],['aws','Technology','Software','AWS','Technology'],['stripe','Merchant Fees','Corporate','Merchant Fees','Finance'],['interest','Debt Service','Debt','Debt / Financing','Finance'],['loan','Debt Service','Debt','Debt / Financing','Finance'],['insurance','Insurance','Corporate','Insurance','Finance'],['legal','Legal / Compliance','Corporate','Legal','Executive'],['accounting','Finance','Team','Finance','Finance']].map(r=>({contains:r[0],costType:r[1],objectType:r[2],object:r[3],team:r[4]}))}
function seed(){return{daily:{},imports:{pioneer:[],bank:[],sage:[],intacct:[],cash:[]},costs:[],people:[],actions:[],rules:rules(),targets:{gpRx:40,costRx:10,fillRate:90,cashFloor:0,minCostCoverage:90}}}
function get(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch(e){return seed()}}
function set(s){localStorage.setItem(KEY,JSON.stringify(s));render()}
function html(x){document.getElementById('appRoot').innerHTML=x}
function toast(m){alert(m)}
function table(h,rows){return `<div class="tablewrap"><table><thead><tr>${h.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${h.length}" class="muted">No rows yet.</td></tr>`}</tbody></table></div>`}
function metric(l,v,s='',cls=''){return `<div class="metric ${cls}"><div class="label">${esc(l)}</div><div class="val">${esc(v)}</div><div class="sub">${esc(s)}</div></div>`}
function pill(x,cls=''){return `<span class="pill ${cls}">${esc(x)}</span>`}
function field(id,label,type='number',val=''){return `<div><label>${esc(label)}</label><input id="${id}" type="${type}" value="${esc(val)}"></div>`}
function sel(id,label,opts,val){return `<div><label>${esc(label)}</label><select id="${id}">${opts.map(o=>`<option ${o===val?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`}
function rowsLast(days){const s=get(),out=[];for(let i=days-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);out.push({date:k,...(s.daily[k]||{})})}return out}
function sum(rows,k){return rows.reduce((a,r)=>a+n(r[k]),0)}
function latest(rows,k){for(let i=rows.length-1;i>=0;i--)if(n(rows[i][k]))return n(rows[i][k]);return 0}
function calc(days=30){const r=rowsLast(days),scripts=sum(r,'scriptsFilled'),received=sum(r,'scriptsReceived'),rev=sum(r,'revenue'),cogs=sum(r,'cogs'),gp=rev-cogs,opCost=sum(r,'labor')+sum(r,'delivery')+sum(r,'storeOpex'),platform=sum(r,'techCost')+sum(r,'corpCost'),growth=sum(r,'salesCost'),debt=sum(r,'debtService'),cost=opCost+platform+growth+debt;return{scripts,received,rev,cogs,gp,opCost,platform,growth,debt,cost,net:gp-cost,gpRx:scripts?gp/scripts:0,costRx:scripts?cost/scripts:0,fill:received?scripts/received*100:0,cash:latest(r,'cash'),ap:latest(r,'ap'),ar:latest(r,'ar'),pa:latest(r,'paBacklog'),ds:latest(r,'dsOhRisk')}}
function costCoverage(){const out=get().costs.filter(r=>r.amount<0),total=out.reduce((a,r)=>a+Math.abs(n(r.amount)),0),mapped=out.filter(r=>r.status!=='Unassigned'&&r.costType!=='Unassigned'&&r.object!=='Unassigned').reduce((a,r)=>a+Math.abs(n(r.amount)),0);return total?mapped/total*100:100}
function unassignedCost(){return get().costs.filter(r=>r.amount<0&&(r.status==='Unassigned'||r.costType==='Unassigned'||r.object==='Unassigned')).reduce((a,r)=>a+Math.abs(n(r.amount)),0)}
function dashboard(){const c=calc(),s=get(),cov=costCoverage();html(`<div class="card hero"><h2>CEO Read</h2><p class="muted">How much does it cost to bring volume in, get it out, and keep the patient on therapy?</p></div><div class="grid">${metric('Scripts',num(c.scripts),'30 day filled')}${metric('Gross Profit',money(c.gp),'GP/Rx '+money(c.gpRx),c.gpRx>=s.targets.gpRx?'good':'warn')}${metric('Cost/Rx',money(c.costRx),'target '+money(s.targets.costRx),c.costRx<=s.targets.costRx?'good':'bad')}${metric('Net',money(c.net),'GP less tracked cost',c.net>=0?'good':'bad')}${metric('Fill Rate',pct(c.fill),'filled / received',c.fill>=s.targets.fillRate?'good':'warn')}${metric('Cash',money(c.cash),'latest')}${metric('Cost Coverage',pct(cov),'mapped cost ledger',cov>=s.targets.minCostCoverage?'good':'bad')}${metric('Unassigned Costs',money(unassignedCost()),'needs ownership',unassignedCost()?'bad':'good')}</div><div class="grid2"><div class="card"><h2>Next Best Actions</h2>${insights(c,cov)}</div><div class="card"><h2>Recent Daily Entries</h2>${table(['Date','Scripts','Revenue','COGS','GP','Cash'],rowsLast(10).reverse().map(r=>[r.date,num(r.scriptsFilled),money(r.revenue),money(r.cogs),money(n(r.revenue)-n(r.cogs)),money(r.cash)]))}</div></div>`)}
function insights(c,cov){let a=[];if(c.gpRx<get().targets.gpRx)a.push(['Margin','GP/Rx is below target. Review payer mix, drug mix, rejects, and Lift opportunities.','amber']);if(c.costRx>get().targets.costRx)a.push(['Cost','Cost/Rx is too high. Review labor, delivery, and overhead.','red']);if(c.fill<get().targets.fillRate)a.push(['Ops','Fill rate is leaking. Check PA, patient contact, payer rejects, and inventory.','red']);if(c.pa)a.push(['PA','PA backlog needs queue ownership. Every stuck PA is GP waiting to become cash.','amber']);if(c.ds)a.push(['Retention','DSOH risk means patients may gap therapy. Run refill rescue.','amber']);if(cov<get().targets.minCostCoverage)a.push(['Finance','Cost ledger mapping is incomplete. Assign unassigned costs before trusting profitability.','red']);if(!a.length)a.push(['Good','No major red flags from entered data. Keep feeding the machine.','green']);return table(['Area','Signal'],a.map(x=>[pill(x[0],x[2]),x[1]]))}
function daily(){const s=get(),d=document.getElementById('dailyDate')?.value||today(),r=s.daily[d]||{};html(`<div class="card"><h2>Daily Entry</h2><div class="form">${field('dailyDate','Date','date',d)}${field('scriptsReceived','Scripts Received','number',r.scriptsReceived)}${field('scriptsFilled','Scripts Filled','number',r.scriptsFilled)}${field('patients','Patients','number',r.patients)}${field('revenue','Revenue','number',r.revenue)}${field('cogs','COGS','number',r.cogs)}${field('labor','Labor','number',r.labor)}${field('delivery','Delivery','number',r.delivery)}${field('storeOpex','Store Opex','number',r.storeOpex)}${field('salesCost','Sales Cost','number',r.salesCost)}${field('techCost','Tech Cost','number',r.techCost)}${field('corpCost','Corporate Cost','number',r.corpCost)}${field('debtService','Debt Service','number',r.debtService)}${field('cash','Cash','number',r.cash)}${field('ap','AP','number',r.ap)}${field('ar','AR','number',r.ar)}${field('paBacklog','PA Backlog','number',r.paBacklog)}${field('dsOhRisk','DSOH Risk','number',r.dsOhRisk)}</div><br><button class="btn primary" onclick="saveDaily()">Save Daily Entry</button></div>`);document.getElementById('dailyDate').onchange=()=>daily()}
function saveDaily(){const s=get(),d=document.getElementById('dailyDate').value;s.daily[d]={};['scriptsReceived','scriptsFilled','patients','revenue','cogs','labor','delivery','storeOpex','salesCost','techCost','corpCost','debtService','cash','ap','ar','paBacklog','dsOhRisk'].forEach(k=>s.daily[d][k]=n(document.getElementById(k).value));set(s);show('dashboard')}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){let ch=text[i],nx=text[i+1];if(ch==='"'&&q&&nx==='"'){cell+='"';i++}else if(ch==='"')q=!q;else if(ch===','&&!q){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&nx==='\n')i++;row.push(cell);if(row.some(x=>String(x).trim()))rows.push(row);row=[];cell=''}else cell+=ch}row.push(cell);if(row.some(x=>String(x).trim()))rows.push(row);let h=(rows.shift()||[]).map(x=>x.trim());return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]??''])))}
function normalizeJSON(x){if(Array.isArray(x))return x;if(x.rows)return x.rows;if(x.data)return x.data;if(x.transactions)return x.transactions;if(x.employees)return x.employees;if(x.actions)return x.actions;return[x]}
function importer(){html(`<div class="card"><h2>Reliable Import</h2><p class="muted">CSV or JSON. Preview first. Then save.</p><div class="form">${sel('importType','Import Type',['pioneer','bank','sage','intacct','cash','costs','people','actions'],'pioneer')}<div><label>File CSV or JSON</label><input id="importFile" type="file" accept=".csv,.json,.txt"></div><div><button class="btn primary" onclick="previewImport()">Preview</button></div><div><button class="btn" onclick="downloadTemplate()">Download Template</button></div></div></div><div id="preview"></div>`)}
async function previewImport(){const f=document.getElementById('importFile').files[0];if(!f)return toast('Choose a file');const t=await f.text();try{previewRows=f.name.toLowerCase().endsWith('.json')?normalizeJSON(JSON.parse(t)):parseCSV(t)}catch(e){console.error(e);return toast('Could not parse file')}let keys=[...new Set(previewRows.slice(0,20).flatMap(r=>Object.keys(r)))].slice(0,10);document.getElementById('preview').innerHTML=`<div class="card"><h2>Preview ${previewRows.length} rows</h2>${table(keys,previewRows.slice(0,25).map(r=>keys.map(k=>esc(r[k]))))}<br><button class="btn primary" onclick="saveImport()">Save Import</button></div>`}
function val(r,...names){for(let nm of names){let k=Object.keys(r||{}).find(x=>x.toLowerCase().replaceAll(' ','').replaceAll('_','')===nm.toLowerCase().replaceAll(' ','').replaceAll('_',''));if(k)return r[k]}return''}
function memoOf(r){return String(val(r,'memo','description','name','vendor','payee','merchant')||'')}
function dateOf(r){return String(val(r,'date','transaction date','posting date')||today()).slice(0,10)}
function costRow(r,source){let debit=n(val(r,'debit','withdrawal')),credit=n(val(r,'credit','deposit')),amount=n(val(r,'amount','transaction amount','net amount'));if(debit)amount=-Math.abs(debit);else if(credit)amount=Math.abs(credit);let memo=memoOf(r);return{id:'c'+Date.now()+Math.random(),date:dateOf(r),source,vendor:val(r,'vendor','payee','merchant','name')||memo,memo,amount,costType:val(r,'costType','cost type')||'Unassigned',objectType:val(r,'objectType','object type')||'Unassigned',object:val(r,'object')||'Unassigned',team:val(r,'team')||'Unassigned',status:amount<0?'Unassigned':'Inflow'}}
function applyCostRules(row,rules){if(row.amount>=0)return row;let text=[row.vendor,row.memo].join(' ').toLowerCase();let rule=(rules||[]).find(r=>text.includes(String(r.contains).toLowerCase()));if(rule){row.costType=rule.costType;row.objectType=rule.objectType;row.object=rule.object;row.team=rule.team;row.status='Auto-Mapped'}return row}
function saveImport(){const type=document.getElementById('importType').value,s=get();if(type==='costs'){previewRows.forEach(r=>s.costs.push(applyCostRules(costRow(r,type),s.rules)))}else if(type==='people'){previewRows.forEach(r=>s.people.push({name:val(r,'name','employee','full name'),role:val(r,'role','title'),team:val(r,'team','department')}))}else if(type==='actions'){previewRows.forEach(r=>s.actions.push({title:val(r,'title','action','task')||memoOf(r),owner:val(r,'owner')||'Unassigned',priority:val(r,'priority')||'Medium',status:val(r,'status')||'Open'}))}else{s.imports[type]=s.imports[type]||[];s.imports[type].push(...previewRows); if(['bank','sage','intacct','cash'].includes(type))previewRows.forEach(r=>s.costs.push(applyCostRules(costRow(r,type),s.rules)))}set(s);previewRows=[];show(type==='costs'||['bank','sage','intacct','cash'].includes(type)?'costs':'importer')}
function downloadTemplate(){const type=document.getElementById('importType').value;let h=type==='costs'||['bank','sage','intacct','cash'].includes(type)?['date','vendor','memo','amount','debit','credit','account']:type==='people'?['name','role','team']:type==='actions'?['title','owner','priority','status']:['date','rxNumber','patientId','doctor','revenue','cogs','grossProfit'];download(type+'-template.csv',h.join(',')+'\n')}
function download(name,text){let b=new Blob([text],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click()}
function rollup(rows,key){let total=rows.reduce((a,r)=>a+Math.abs(n(r.amount)),0),o={};rows.forEach(r=>{let k=r[key]||'Unassigned';o[k]=(o[k]||0)+Math.abs(n(r.amount))});return Object.entries(o).sort((a,b)=>b[1]-a[1]).map(([k,v])=>[esc(k),money(v),pct(total?v/total*100:0)])}
function costs(){const s=get(),rows=s.costs,out=rows.filter(r=>r.amount<0),un=out.filter(r=>r.status==='Unassigned'||r.costType==='Unassigned'||r.object==='Unassigned');html(`<div class="grid">${metric('Outflows',money(out.reduce((a,r)=>a+Math.abs(r.amount),0)),out.length+' rows')}${metric('Cost Coverage',pct(costCoverage()),'mapped dollars',costCoverage()>=s.targets.minCostCoverage?'good':'bad')}${metric('Unassigned',money(unassignedCost()),un.length+' rows',un.length?'bad':'good')}${metric('Rules',num(s.rules.length),'auto-classification')}</div><div class="card"><div class="btns"><button class="btn primary" onclick="show('importer')">Import Costs</button><button class="btn" onclick="autoMapCosts()">Run Auto Map</button><button class="btn" onclick="bulkAssignCosts()">Bulk Assign Unassigned</button><button class="btn" onclick="exportCosts()">Export Costs</button></div></div><div class="grid2"><div class="card"><h2>Cost by Type</h2>${table(['Cost Type','Amount','%'],rollup(out,'costType'))}</div><div class="card"><h2>Cost by Team</h2>${table(['Team','Amount','%'],rollup(out,'team'))}</div></div><div class="card"><h2>Cost Rows</h2>${table(['Date','Vendor','Memo','Amount','Cost Type','Object','Team','Status','Edit'],rows.map((r,i)=>[r.date,esc(r.vendor),esc(r.memo),money(r.amount),esc(r.costType),esc(r.object),esc(r.team),r.status,`<button class="btn" onclick="editCost(${i})">Edit</button>`]))}</div><div class="card"><h2>Rules</h2>${renderRules()}</div>`)}
function renderRules(){const s=get();return `${table(['Contains','Cost Type','Object','Team','Delete'],s.rules.map((r,i)=>[esc(r.contains),esc(r.costType),esc(r.object),esc(r.team),`<button class="btn red" onclick="deleteRule(${i})">Delete</button>`]))}<br><div class="form">${field('ruleContains','Contains','text')}${field('ruleCostType','Cost Type','text')}${field('ruleObject','Object','text')}${field('ruleTeam','Team','text')}<div><button class="btn primary" onclick="addRule()">Add Rule</button></div></div>`}
function addRule(){const s=get();s.rules.push({contains:document.getElementById('ruleContains').value,costType:document.getElementById('ruleCostType').value,objectType:'Rule',object:document.getElementById('ruleObject').value,team:document.getElementById('ruleTeam').value});set(s);show('costs')}
function deleteRule(i){const s=get();s.rules.splice(i,1);set(s);show('costs')}
function autoMapCosts(){const s=get();s.costs=s.costs.map(r=>applyCostRules(r,s.rules));set(s);show('costs')}
function editCost(i){const s=get(),r=s.costs[i];r.costType=prompt('Cost type',r.costType)||r.costType;r.object=prompt('Object/location/channel/team',r.object)||r.object;r.team=prompt('Team',r.team)||r.team;r.status='Mapped';set(s);show('costs')}
function bulkAssignCosts(){const s=get(),ct=prompt('Cost type for all unassigned outflows?','Other');if(!ct)return;const obj=prompt('Object/location/channel?','Corporate')||'Corporate';const team=prompt('Team?','Finance')||'Finance';s.costs.forEach(r=>{if(r.amount<0&&r.status==='Unassigned'){r.costType=ct;r.object=obj;r.team=team;r.status='Mapped'}});set(s);show('costs')}
function exportCosts(){const rows=get().costs,h=['date','source','vendor','memo','amount','costType','object','team','status'];download('onpoint-costs.csv',h.join(',')+'\n'+rows.map(r=>h.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(',')).join('\n'))}
function pnl(){const c=calc(),out=get().costs.filter(r=>r.amount<0),ledgerCost=out.reduce((a,r)=>a+Math.abs(r.amount),0);html(`<div class="grid">${metric('Revenue',money(c.rev),'30 days')}${metric('COGS',money(c.cogs),'daily entries')}${metric('Gross Profit',money(c.gp),'GP/Rx '+money(c.gpRx))}${metric('Net Contribution',money(c.net),'daily GP less tracked daily costs',c.net>=0?'good':'bad')}</div><div class="card"><h2>P&L Bridge</h2>${table(['Line','Amount','Meaning'],[['Revenue',money(c.rev),'Top line'],['COGS','-'+money(c.cogs),'Drug cost'],['Gross Profit',money(c.gp),'Revenue minus COGS'],['Operating Cost','-'+money(c.opCost),'Labor + delivery + store opex'],['Growth Cost','-'+money(c.growth),'Sales / BD'],['Platform Cost','-'+money(c.platform),'Tech + corporate'],['Debt Service','-'+money(c.debt),'Financing drag'],['Net Contribution',money(c.net),'GP minus tracked costs'],['Cost Ledger Outflows',money(ledgerCost),'Imported/assigned costs, separate from daily P&L']])}</div><div class="card"><h2>Unit Economics</h2>${table(['Metric','Value'],[['GP/Rx',money(c.gpRx)],['Cost/Rx',money(c.costRx)],['Cost/$GP',money(c.gp?c.cost/c.gp:0)],['Revenue/Rx',money(c.scripts?c.rev/c.scripts:0)],['Breakeven Scripts',num(Math.ceil(c.cost/(c.gpRx||1)))],['AP minus AR',money(c.ap-c.ar)]])}</div>`)}
function reconcile(){const s=get(),bank=s.imports.bank.concat(s.imports.cash).map(r=>costRow(r,'bank')).filter(r=>r.amount<0),sage=s.imports.sage.concat(s.imports.intacct).map(r=>costRow(r,'sage')).filter(r=>r.amount<0),ledger=s.costs.filter(r=>r.amount<0),un=s.costs.filter(r=>r.amount<0&&r.status==='Unassigned');html(`<div class="grid">${metric('Bank Outflows',money(bank.reduce((a,r)=>a+Math.abs(r.amount),0)),bank.length+' rows')}${metric('Sage Outflows',money(sage.reduce((a,r)=>a+Math.abs(r.amount),0)),sage.length+' rows')}${metric('Cost Ledger',money(ledger.reduce((a,r)=>a+Math.abs(r.amount),0)),ledger.length+' rows')}${metric('Unassigned',money(un.reduce((a,r)=>a+Math.abs(r.amount),0)),un.length+' rows',un.length?'bad':'good')}</div><div class="card"><h2>Close Checklist</h2>${table(['Step','Status'],[['Bank imported',bank.length?pill('Done','green'):pill('Missing','red')],['Sage/Intacct imported',sage.length?pill('Done','green'):pill('Missing','amber')],['Cost ledger populated',ledger.length?pill('Done','green'):pill('Missing','red')],['Costs assigned',un.length?pill('Open','red'):pill('Clean','green')]])}</div><div class="card"><h2>Unassigned Costs</h2>${table(['Date','Vendor','Amount','Memo'],un.map(r=>[r.date,esc(r.vendor),money(r.amount),esc(r.memo)]))}</div>`)}
function forecast(){const c=calc(),weeks=[];let cash=c.cash;for(let i=1;i<=13;i++){let scripts=Math.round(c.scripts/30*7),gp=scripts*c.gpRx,cost=scripts*c.costRx,net=gp-cost;cash+=net;weeks.push(['Week '+i,num(scripts),money(gp),money(cost),money(net),money(cash),cash<get().targets.cashFloor?pill('Below floor','red'):pill('OK','green')])}html(`<div class="card"><h2>13 Week Simple Forecast</h2>${table(['Week','Scripts','GP','Cost','Net','Ending Cash','Signal'],weeks)}</div>`)}
function people(){const s=get();html(`<div class="card"><div class="form">${field('pname','Name','text')}${field('prole','Role','text')}${field('pteam','Team','text')}<div><button class="btn primary" onclick="addPerson()">Add Person</button></div></div></div>${table(['Name','Role','Team','Delete'],s.people.map((p,i)=>[esc(p.name),esc(p.role),esc(p.team),`<button class="btn red" onclick="delPerson(${i})">Delete</button>`]))}`)}
function addPerson(){const s=get();s.people.push({name:document.getElementById('pname').value,role:document.getElementById('prole').value,team:document.getElementById('pteam').value});set(s);show('people')}
function delPerson(i){const s=get();s.people.splice(i,1);set(s);show('people')}
function actions(){const s=get();html(`<div class="card"><div class="form">${field('atitle','Action','text')}${sel('aowner','Owner',['Unassigned'].concat(s.people.map(p=>p.name)),'Unassigned')}${sel('apriority','Priority',['High','Medium','Low'],'Medium')}<div><button class="btn primary" onclick="addAction()">Add Action</button></div></div></div>${table(['Action','Owner','Priority','Status','Done'],s.actions.map((a,i)=>[esc(a.title),esc(a.owner),a.priority,a.status,`<button class="btn green" onclick="doneAction(${i})">Done</button>`]))}`)}
function addAction(){const s=get();s.actions.push({title:document.getElementById('atitle').value,owner:document.getElementById('aowner').value,priority:document.getElementById('apriority').value,status:'Open'});set(s);show('actions')}
function doneAction(i){const s=get();s.actions[i].status='Done';set(s);show('actions')}
function dataqa(){const s=get(),issues=[];if(!Object.keys(s.daily).length)issues.push(['Daily data',pill('Missing','red'),'No daily entries yet']);if(!s.costs.length)issues.push(['Cost data',pill('Missing','red'),'No cost ledger rows']);if(unassignedCost())issues.push(['Cost mapping',pill('Open','red'),money(unassignedCost())+' unassigned']);if(!s.people.length)issues.push(['People',pill('Missing','amber'),'No employees/owners']);if(!s.actions.length)issues.push(['Actions',pill('Missing','amber'),'No actions created']);if(!issues.length)issues.push(['Data QA',pill('Good','green'),'No obvious issues']);html(`<div class="card"><h2>Data Quality Checks</h2>${table(['Area','Status','Detail'],issues)}</div><div class="card"><h2>Storage</h2>${table(['Dataset','Rows'],[['Daily entries',Object.keys(s.daily).length],['PioneerRx imports',s.imports.pioneer.length],['Bank imports',s.imports.bank.length],['Sage/Intacct imports',s.imports.sage.length+s.imports.intacct.length],['Cost ledger',s.costs.length],['People',s.people.length],['Actions',s.actions.length]])}</div>`)}
function settings(){const s=get();html(`<div class="card"><h2>Targets</h2><div class="form">${field('tgpRx','Target GP/Rx','number',s.targets.gpRx)}${field('tcostRx','Target Cost/Rx','number',s.targets.costRx)}${field('tfill','Target Fill Rate','number',s.targets.fillRate)}${field('tcash','Cash Floor','number',s.targets.cashFloor)}${field('tcov','Min Cost Coverage %','number',s.targets.minCostCoverage)}</div><br><button class="btn primary" onclick="saveSettings()">Save Targets</button></div><div class="card bad"><h2>Reset</h2><p class="muted">This clears only Stable v2 data.</p><button class="btn red" onclick="resetApp()">Clear Stable v2 Data</button></div>`)}
function saveSettings(){const s=get();s.targets={gpRx:n(document.getElementById('tgpRx').value),costRx:n(document.getElementById('tcostRx').value),fillRate:n(document.getElementById('tfill').value),cashFloor:n(document.getElementById('tcash').value),minCostCoverage:n(document.getElementById('tcov').value)};set(s);show('dashboard')}
function exportAll(){let b=new Blob([JSON.stringify(get(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='onpoint-stable-v2-backup-'+today()+'.json';a.click()}
async function importBackup(e){const f=e.target.files[0];if(!f)return;const txt=await f.text();localStorage.setItem(KEY,txt);render();show('dashboard')}
function resetApp(){if(confirm('Clear stable v2 app data?')){localStorage.removeItem(KEY);render();show('dashboard')}}
function show(id){current=id;document.getElementById('title').textContent=pages.find(p=>p[0]===id)?.[1]||id;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.id===id));render()}
function render(){({dashboard,daily,importer,costs,pnl,reconcile,forecast,people,actions,dataqa,settings}[current]||dashboard)()}
function init(){document.getElementById('nav').innerHTML=pages.map(p=>`<button data-id="${p[0]}" onclick="show('${p[0]}')">${p[1]}</button>`).join('');document.getElementById('menuBtn').onclick=()=>document.getElementById('nav').classList.toggle('open');document.getElementById('exportBackup').onclick=exportAll;document.getElementById('importBackupBtn').onclick=()=>document.getElementById('backupFile').click();document.getElementById('backupFile').onchange=importBackup;show('dashboard')}
init();