"use strict";
const KEY="opdash.pages.v1",AUTH="opdash.auth.v1";
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
const addDays=(d,n)=>{let x=new Date(d+"T00:00:00");x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const n=x=>Number(x)||0,fmt=x=>Math.round(n(x)).toLocaleString(),money=x=>"$"+fmt(x),pct=x=>isFinite(x)?Number(x).toFixed(1)+"%":"0.0%",ratio=x=>isFinite(x)?Number(x).toFixed(2):"0.00";
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const csvSafe=v=>{let s=String(v??"");if(/^[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};
function toast(m){$("toast").textContent=m;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),2500)}
async function sha(s){let b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function seed(){return{manual:{},imports:{pioneer:[],cash:[],intacct:[],powerbi:[]},targets:{gpRx:40,costRx:10,fillRate:90,adherence:85,costGp:.35,timeToStart:24},cashForecast:[],teamNotes:{}}}
function db(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch(e){return seed()}}
function saveDb(d){localStorage.setItem(KEY,JSON.stringify(d));storage()}
function storage(){let u=0;for(let k in localStorage)if(Object.hasOwn(localStorage,k))u+=localStorage[k].length+k.length;let el=$("storageTxt")||document.querySelector(".mini-muted");if(el)el.textContent=(u/1024).toFixed(0)+" KB used locally"}
function range(){return[$("rangeStart").value||$("start")?.value||today(),$("rangeEnd").value||$("end")?.value||today()]}
function inR(x,a,b){x=String(x||"").slice(0,10);return x>=a&&x<=b}
function imported(t){let [a,b]=range();return(db().imports[t]||[]).filter(r=>inR(r.date,a,b))}
function manuals(){let [a,b]=range(),m=db().manual;return Object.keys(m).filter(k=>k>=a&&k<=b).map(k=>({date:k,...m[k]}))}
function fields(){return["patients","newPatients","scriptsReceived","scriptsFilled","scriptsReversed","scriptsAbandoned","refillsDue","refillsCaptured","revenue","cogs","labor","delivery","storeOpex","salesCost","techCost","enterpriseCost","corpCost","activeDoctors","newDoctors","enterpriseAccounts","cash","ar","ap","debt","paBacklog","paSubmitted","paApproved","paDenied","firstFills","secondFills","dsOhRisk","dirExposure","deliveries","deliveryFailures","deliveryFirst","laborHours"]}
function label(k){return k.replace(/([A-Z])/g," $1").replace(/^./,s=>s.toUpperCase()).replace("Gp","GP").replace("Pa","PA").replace("Ds Oh","DSOH")}
function calc(){let mode=($("dataMode")||$("mode")).value,o={patients:0,newPatients:0,scriptsReceived:0,scriptsFilled:0,scriptsReversed:0,scriptsAbandoned:0,refillsDue:0,refillsCaptured:0,revenue:0,cogs:0,gp:0,labor:0,delivery:0,storeOpex:0,salesCost:0,techCost:0,enterpriseCost:0,corpCost:0,activeDoctors:0,newDoctors:0,enterpriseAccounts:0,cash:0,ar:0,ap:0,debt:0,paBacklog:0,paSubmitted:0,paApproved:0,paDenied:0,firstFills:0,secondFills:0,dsOhRisk:0,dirExposure:0,deliveries:0,deliveryFailures:0,deliveryFirst:0,laborHours:0,adh:[],time:[]};
 let addM=r=>{fields().forEach(k=>o[k]+=n(r[k]));if(n(r.adherence))o.adh.push(n(r.adherence));if(n(r.timeToStart))o.time.push(n(r.timeToStart))};
 let addP=r=>{o.scriptsReceived++;let st=String(r.status||"").toLowerCase();if(st.includes("fill"))o.scriptsFilled++;if(st.includes("reverse"))o.scriptsReversed++;if(st.includes("abandon"))o.scriptsAbandoned++;o.revenue+=n(r.revenue);o.cogs+=n(r.cogs);o.gp+=n(r.grossProfit);if(n(r.adherencePct))o.adh.push(n(r.adherencePct));if(n(r.timeToStartHours))o.time.push(n(r.timeToStartHours));let pa=String(r.paStatus||"").toLowerCase();if(pa.includes("submitted"))o.paSubmitted++;if(pa.includes("approved"))o.paApproved++;if(pa.includes("denied"))o.paDenied++;if(String(r.isFirstFill).toLowerCase()==="yes")o.firstFills++;if(String(r.isSecondFill).toLowerCase()==="yes")o.secondFills++;if(r.dsOhDays!==""&&n(r.dsOhDays)<=7)o.dsOhRisk++};
 let addI=r=>{let t=String(r.accountType||"").toLowerCase(),a=n(r.amount);if(t==="revenue")o.revenue+=a;else if(t==="cogs")o.cogs+=a;else if(t==="labor")o.labor+=Math.abs(a);else if(t==="delivery")o.delivery+=Math.abs(a);else if(t.includes("store")||t==="rent")o.storeOpex+=Math.abs(a);else if(t==="sales")o.salesCost+=Math.abs(a);else if(t==="technology")o.techCost+=Math.abs(a);else if(t==="enterprise")o.enterpriseCost+=Math.abs(a);else if(["corporate","finance","admin"].includes(t))o.corpCost+=Math.abs(a);else if(t==="cash")o.cash+=a;else if(["ar","receivables"].includes(t))o.ar+=a;else if(["ap","payables"].includes(t))o.ap+=Math.abs(a);else if(t==="debt")o.debt+=Math.abs(a);else if(t==="dir")o.dirExposure+=Math.abs(a)};
 let addC=r=>{let c=String(r.category||"").toLowerCase(),a=Math.abs(n(r.amount));if(c==="labor")o.labor+=a;else if(c==="delivery")o.delivery+=a;else if(c.includes("store")||c.includes("rent"))o.storeOpex+=a;else if(c==="sales")o.salesCost+=a;else if(c.includes("tech"))o.techCost+=a;else if(c==="enterprise")o.enterpriseCost+=a;else if(["corporate","finance","admin"].includes(c))o.corpCost+=a};
 let addB=r=>{o.patients+=n(r.patients);o.scriptsReceived+=n(r.scriptsReceived);o.scriptsFilled+=n(r.scriptsFilled);o.revenue+=n(r.revenue);o.cogs+=n(r.cogs);o.gp+=n(r.grossProfit);if(n(r.adherencePct))o.adh.push(n(r.adherencePct))};
 if(mode!=="imported")manuals().forEach(addM);if(mode!=="manual"){imported("pioneer").forEach(addP);imported("intacct").forEach(addI);imported("cash").forEach(addC);imported("powerbi").forEach(addB)}
 if(!o.gp)o.gp=o.revenue-o.cogs;else if(o.revenue||o.cogs)o.gp+=o.revenue-o.cogs;o.ops=o.labor+o.delivery+o.storeOpex;o.total=o.ops+o.salesCost+o.techCost+o.enterpriseCost+o.corpCost;o.ebitda=o.gp-o.total;o.fill=o.scriptsReceived?o.scriptsFilled/o.scriptsReceived*100:0;o.leak=o.scriptsReceived?(o.scriptsReversed+o.scriptsAbandoned)/o.scriptsReceived*100:0;o.refill=o.refillsDue?o.refillsCaptured/o.refillsDue*100:0;o.adherence=o.adh.length?o.adh.reduce((a,b)=>a+b,0)/o.adh.length:0;o.timeToStart=o.time.length?o.time.reduce((a,b)=>a+b,0)/o.time.length:0;o.gpRx=o.scriptsFilled?o.gp/o.scriptsFilled:0;o.costRx=o.scriptsFilled?o.ops/o.scriptsFilled:0;o.costGp=o.gp?o.ops/o.gp:0;o.paApproval=o.paSubmitted?o.paApproved/o.paSubmitted*100:0;o.firstSecond=o.firstFills?o.secondFills/o.firstFills*100:0;o.breakeven=o.gpRx?Math.ceil(o.total/o.gpRx):0;o.deliverySuccess=o.deliveries?100-o.deliveryFailures/o.deliveries*100:0;o.firstDelivery=o.deliveries?o.deliveryFirst/o.deliveries*100:0;return o}
function metric(k,v,h="",cls=""){return`<div class="card metric"><div class="k">${esc(k)}</div><div class="v ${cls}">${esc(v)}</div><div class="h">${esc(h)}</div></div>`}
function table(h,r){return`<div class="table-wrap"><table><thead><tr>${h.map(x=>`<th>${esc(x)}</th>`).join("")}</tr></thead><tbody>${r.map(x=>`<tr>${x.map(c=>`<td>${c}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function cashForecast(){let d=db(),cash=n(calc().cash),out=[];for(let i=0;i<13;i++){let r=d.cashForecast[i]||{inflow:0,outflow:0};cash+=n(r.inflow)-n(r.outflow);out.push({week:i+1,inflow:n(r.inflow),outflow:n(r.outflow),ending:cash})}return out}
function cashLow(){return Math.min(...cashForecast().map(x=>x.ending),calc().cash||0)}
function alerts(c){let t=db().targets,a=[];if(c.fill<t.fillRate)a.push(["Fill Rate",`Below target: ${pct(c.fill)}. Check PA, rejections, patient contact, inventory.`,"bad"]);if(c.gpRx<t.gpRx)a.push(["GP/Rx",`Below target: ${money(c.gpRx)}. Check payer mix, DIR, drug mix.`,"warn"]);if(c.costRx>t.costRx)a.push(["Cost/Rx",`Too high: ${money(c.costRx)}. Check labor, delivery, opex.`,"bad"]);if(c.paBacklog>0)a.push(["PA Backlog",`${fmt(c.paBacklog)} scripts waiting on PA.`,"warn"]);if(c.dsOhRisk>0)a.push(["DSOH Risk",`${fmt(c.dsOhRisk)} patients near therapy gap.`,"warn"]);if(cashLow()<0)a.push(["Cash Forecast","13-week cash forecast goes negative.","bad"]);if(!a.length)a.push(["Clean Board","No major red flags from entered/imported data.","good"]);return a}
function renderCommand(){let c=calc(),t=db().targets;$("view-command").innerHTML=`<div class="grid">${metric("Gross Profit",money(c.gp),"Revenue minus COGS",c.gp>=0?"good":"bad")}${metric("EBITDA Proxy",money(c.ebitda),"GP minus listed costs",c.ebitda>=0?"good":"bad")}${metric("Fill Rate",pct(c.fill),"Target "+pct(t.fillRate),c.fill>=t.fillRate?"good":"bad")}${metric("Breakeven Rx",fmt(c.breakeven),"Filled minus line: "+fmt(c.scriptsFilled-c.breakeven),c.scriptsFilled>=c.breakeven?"good":"bad")}${metric("PA Backlog",fmt(c.paBacklog),"Invisible leakage driver",c.paBacklog?"warn":"good")}${metric("First to Second Fill",pct(c.firstSecond),"Core retention metric",c.firstSecond>=70?"good":"warn")}${metric("DSOH Risk",fmt(c.dsOhRisk),"Patients at risk within 7 days",c.dsOhRisk?"warn":"good")}${metric("13-Week Low Cash",money(cashLow()),"Lowest projected ending cash",cashLow()>=0?"good":"bad")}</div><h2>Executive Alerts</h2><div class="grid3">${alerts(c).map(a=>`<div class="card"><span class="pill">${esc(a[0])}</span><p class="${a[2]}" style="font-weight:900">${esc(a[1])}</p></div>`).join("")}</div><h2>30-Day Trends</h2><div class="grid">${trend("GP","gp")}${trend("Fill Rate","fill")}${trend("Cost/Rx","cost")}${trend("Adherence","adherence")}</div>`}
function trend(name,type){let d=db().manual,dates=Object.keys(d).sort().slice(-30),vals=dates.map(dt=>{let r=d[dt],gp=n(r.revenue)-n(r.cogs),ops=n(r.labor)+n(r.delivery)+n(r.storeOpex);if(type==="gp")return gp;if(type==="fill")return n(r.scriptsReceived)?n(r.scriptsFilled)/n(r.scriptsReceived)*100:0;if(type==="cost")return n(r.scriptsFilled)?ops/n(r.scriptsFilled):0;return n(r.adherence)}),last=vals.at(-1)||0;return metric(name,type==="gp"||type==="cost"?money(last):pct(last),"last "+dates.length+" saved manual days")}
function renderDaily(){let d=db(),dt=$("rangeEnd").value||today(),m=d.manual[dt]||{};$("view-daily").innerHTML=`<div class="notice">Daily manual entry for ${esc(dt)}.</div><div class="card grid">${fields().map(k=>`<div><label>${esc(label(k))}</label><input id="m_${k}" value="${esc(m[k]??0)}" type="number"></div>`).join("")}<div><label>Adherence %</label><input id="m_adherence" value="${esc(m.adherence??0)}" type="number"></div><div><label>Time To Start Hours</label><input id="m_timeToStart" value="${esc(m.timeToStart??0)}" type="number"></div><div style="grid-column:1/-1"><label>Notes</label><textarea id="m_notes">${esc(m.notes||"")}</textarea></div></div><button class="btn primary" onclick="saveManual()">Save Day</button>`}
function saveManual(){let d=db(),dt=$("rangeEnd").value||today(),o={};fields().forEach(k=>o[k]=$("m_"+k)?.value||0);o.adherence=$("m_adherence").value;o.timeToStart=$("m_timeToStart").value;o.notes=$("m_notes").value;d.manual[dt]=o;saveDb(d);toast("Saved day");render()}
function renderImports(){let types=[["pioneer","PioneerRx Scripts"],["cash","Cash / Bank Export"],["intacct","Sage Intacct"],["powerbi","Power BI Summary"]];$("view-imports").innerHTML=`<div class="grid">${types.map(([t,nm])=>`<div class="card"><h3>${nm}</h3><input id="file_${t}" type="file" accept=".csv,.json"><button class="btn primary" onclick="importFile('${t}')">Import</button><button class="btn" onclick="tmpl('${t}')">Template</button><p class="muted">${fmt((db().imports[t]||[]).length)} imported rows</p></div>`).join("")}</div><h2>Import Quality</h2><div class="grid">${types.map(([t,nm])=>metric(nm,fmt((db().imports[t]||[]).length),"rows")).join("")}</div>`}
async function importFile(t){let f=$("file_"+t).files[0];if(!f)return toast("Choose file");let txt=await f.text(),rows=f.name.endsWith(".json")?(JSON.parse(txt).rows||JSON.parse(txt).data||JSON.parse(txt)):parseCSV(txt);rows=rows.map(r=>norm(t,r)).filter(r=>r.date);let d=db();d.imports[t]=(d.imports[t]||[]).concat(rows);saveDb(d);toast("Imported "+rows.length+" rows");render()}
function get(r,...ks){for(let k of ks){let h=Object.keys(r).find(x=>x.toLowerCase().replaceAll(" ","")===k.toLowerCase().replaceAll(" ",""));if(h!=null)return r[h]}return""}
function norm(t,r){if(t==="pioneer")return{date:get(r,"date","fillDate","rxDate").slice(0,10),rxNumber:get(r,"rxNumber","rx"),patientId:get(r,"patientId"),doctor:get(r,"doctor","prescriber"),location:get(r,"location","store"),channel:get(r,"channel","source"),status:get(r,"status"),revenue:get(r,"revenue","amountPaid"),cogs:get(r,"cogs","drugCost"),grossProfit:get(r,"grossProfit","gp"),timeToStartHours:get(r,"timeToStartHours"),adherencePct:get(r,"adherencePct","pdc"),payer:get(r,"payer"),drugName:get(r,"drugName","drug"),ndc:get(r,"ndc"),paStatus:get(r,"paStatus"),rejectCode:get(r,"rejectCode","rejectionCode"),payerType:get(r,"payerType"),drugClass:get(r,"drugClass"),isFirstFill:get(r,"isFirstFill"),isSecondFill:get(r,"isSecondFill"),dsOhDays:get(r,"dsOhDays","daysSupplyOnHand")};if(t==="cash")return{date:get(r,"date").slice(0,10),account:get(r,"account"),description:get(r,"description","memo"),amount:get(r,"amount"),category:get(r,"category"),location:get(r,"location"),team:get(r,"team")};if(t==="intacct")return{date:get(r,"date").slice(0,10),location:get(r,"location"),account:get(r,"account"),accountType:get(r,"accountType","type"),amount:get(r,"amount"),department:get(r,"department"),vendor:get(r,"vendor"),customer:get(r,"customer")};return{date:get(r,"date").slice(0,10),location:get(r,"location"),channel:get(r,"channel"),doctor:get(r,"doctor"),enterpriseAccount:get(r,"enterpriseAccount","account"),patients:get(r,"patients"),scriptsReceived:get(r,"scriptsReceived"),scriptsFilled:get(r,"scriptsFilled"),revenue:get(r,"revenue"),cogs:get(r,"cogs"),grossProfit:get(r,"grossProfit","gp"),adherencePct:get(r,"adherencePct"),fillRatePct:get(r,"fillRatePct")}}
function parseCSV(txt){let rows=[],row=[],cell="",q=false;for(let i=0;i<txt.length;i++){let ch=txt[i],nx=txt[i+1];if(ch==='"'&&q&&nx==='"'){cell+='"';i++}else if(ch==='"')q=!q;else if(ch===','&&!q){row.push(cell);cell=""}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&nx==='\n')i++;row.push(cell);if(row.some(x=>x!==""))rows.push(row);row=[];cell=""}else cell+=ch}row.push(cell);if(row.some(x=>x!==""))rows.push(row);let h=rows.shift()||[];return rows.map(r=>Object.fromEntries(h.map((x,i)=>[x.trim(),r[i]??""])))}
function renderFinance(){let c=calc(),w=cashForecast();$("view-ledgers")&&($("view-ledgers").id="view-finance");let el=$("view-finance")||$("view-ledgers");el.innerHTML=`<div class="grid">${metric("Cash",money(c.cash),"current")}${metric("AR",money(c.ar),"receivables")}${metric("AP + Debt",money(c.ap+c.debt),"cash out risk")}${metric("Breakeven Scripts",fmt(c.breakeven),"one number every day")}</div><h2>13-Week Cash Forecast</h2>${table(["Week","Cash In","Cash Out","Ending"],w.map(x=>[fmt(x.week),money(x.inflow),money(x.outflow),`<span class="${x.ending<0?'bad':'good'}">${money(x.ending)}</span>`]))}<button class="btn primary" onclick="editForecast()">Edit Forecast</button>`}
function editForecast(){let d=db(),el=$("view-finance")||$("view-ledgers");el.innerHTML=`<div class="card grid2">${Array.from({length:13},(_,i)=>`<div><label>Week ${i+1} Cash In</label><input id="fi_${i}" value="${esc((d.cashForecast[i]||{}).inflow||0)}"></div><div><label>Week ${i+1} Cash Out</label><input id="fo_${i}" value="${esc((d.cashForecast[i]||{}).outflow||0)}"></div>`).join("")}</div><button class="btn primary" onclick="saveForecast()">Save Forecast</button>`}
function saveForecast(){let d=db();d.cashForecast=Array.from({length:13},(_,i)=>({inflow:n($("fi_"+i).value),outflow:n($("fo_"+i).value)}));saveDb(d);render()}
function renderPA(){let c=calc(),p=imported("pioneer"),rej=group(p,r=>r.rejectCode||"None"),payer=group(p,r=>r.payer||"Unknown");let el=$("view-pa")||document.createElement('section');if(!$("view-pa"))return;el.innerHTML=`<div class="grid">${metric("PA Backlog",fmt(c.paBacklog),"waiting on PA")}${metric("PA Approval Rate",pct(c.paApproval),"approved / submitted")}${metric("Avg Cycle Proxy",ratio(c.timeToStart)+" hrs","until PA timestamps exist")}${metric("Rejection Codes",fmt(Object.keys(rej).length),"distinct")}</div><h2>Top Rejection Codes</h2>${groupTable(rej,"Code")}<h2>Payer Mix</h2>${groupTable(payer,"Payer")}`}
function renderRetention(){let c=calc();let el=$("view-retention");if(!el)return;el.innerHTML=`<div class="grid">${metric("First to Second Fill",pct(c.firstSecond),"core retention")}${metric("DSOH Risk",fmt(c.dsOhRisk),"within 7 days")}${metric("Refill Capture",pct(c.refill),"captured / due")}${metric("Adherence",pct(c.adherence),"PDC proxy")}</div><h2>Patient Abandonment Funnel</h2>${funnel(["Script Received","PA Submitted","PA Approved","Insurance Billed","Patient Contacted","Picked Up / Delivered"],[c.scriptsReceived,c.paSubmitted,c.paApproved,c.scriptsFilled+c.scriptsReversed,c.scriptsFilled,c.scriptsFilled])}`}
function funnel(l,v){let m=Math.max(...v,1);return`<div class="card">${l.map((x,i)=>`<div style="margin:10px 0"><b>${esc(x)}</b><span style="float:right">${fmt(v[i])}</span><div class="bar"><span style="width:${v[i]/m*100}%"></span></div></div>`).join("")}</div>`}
function renderTeams(){let c=calc();$("view-teams").innerHTML=`<div class="grid5">${metric("Sales",money(c.gp),"GP in; doctors "+fmt(c.activeDoctors))}${metric("Enterprise",money(c.enterpriseAccounts?c.gp/c.enterpriseAccounts:0),"GP/account")}${metric("Ops",pct(c.fill),"fill rate; cost/rx "+money(c.costRx))}${metric("Tech",ratio(c.gp?c.techCost/c.gp:0),"tech cost / GP")}${metric("Finance",money(c.ebitda),"truth")}</div><h2>Team Notes</h2><div class="grid5">${["sales","enterprise","ops","tech","finance"].map(t=>`<div class="card"><h3>${label(t)}</h3><textarea id="note_${t}">${esc((db().teamNotes||{})[t]||"")}</textarea><button class="btn" onclick="saveNote('${t}')">Save</button></div>`).join("")}</div>`}
function saveNote(t){let d=db();d.teamNotes=d.teamNotes||{};d.teamNotes[t]=$("note_"+t).value;saveDb(d);toast("Saved note")}
function group(a,fn){let g={};a.forEach(r=>{let k=fn(r)||"Unknown";(g[k]=g[k]||[]).push(r)});return g}
function groupTable(g,name){let rs=Object.entries(g).map(([k,a])=>{let rev=a.reduce((s,r)=>s+n(r.revenue),0),cogs=a.reduce((s,r)=>s+n(r.cogs),0),gp=a.reduce((s,r)=>s+n(r.grossProfit||r.gp),0);if(!gp)gp=rev-cogs;return[esc(k),fmt(a.length),money(rev),money(gp),money(a.length?gp/a.length:0)]});return table([name,"Rows/Scripts","Revenue","GP","GP/Row"],rs)}
function renderChannels(){$("view-channels").innerHTML="<h2>Channel Economics</h2>"+groupTable(group(imported("pioneer").concat(imported("powerbi")),r=>r.channel||"Unknown"),"Channel")}
function renderLocations(){$("view-locations").innerHTML="<h2>Location Economics</h2>"+groupTable(group(imported("pioneer").concat(imported("powerbi")),r=>r.location||"Unknown"),"Location")}
function renderDoctors(){let p=imported("pioneer"),g=group(p,r=>r.doctor||"Unknown"),rs=Object.entries(g).map(([k,a])=>{let gp=a.reduce((s,r)=>s+n(r.grossProfit),0),last=a.map(r=>r.date).sort().pop(),days=last?Math.floor((new Date(today())-new Date(last))/864e5):999;return[esc(k),fmt(a.length),money(gp),esc(last||""),`<span class="${days>30?'bad':days>14?'warn':'good'}">${days>30?'Churn risk':days>14?'Watch':'Active'}</span>`]});$("view-doctors").innerHTML='<div class="notice">Doctor tiering protects the 20% driving 80%.</div>'+table(["Doctor","Scripts","GP","Last Script","Risk"],rs)}
function renderEnterprise(){$("view-enterprise").innerHTML='<h2>Enterprise Account Value</h2>'+groupTable(group(imported("powerbi"),r=>r.enterpriseAccount||"Unknown"),"Account")+`<h2>Products</h2><div class="grid3">${metric("Medical Groups","Access + adherence","therapy starts, gaps, leakage")}${metric("Pharma","Start + persistence","abandonment and continuation")}${metric("Payors","Adherence + cost","risk list and lower-cost routing")}</div>`}
function renderDrugs(){let p=imported("pioneer"),el=$("view-drugs");if(!el)return;el.innerHTML='<h2>Top Drugs by GP</h2>'+groupTable(group(p,r=>r.drugName||"Unknown"),"Drug")+'<h2>Drug Class GP</h2>'+groupTable(group(p,r=>r.drugClass||"Unknown"),"Class")+'<h2>Payer Type</h2>'+groupTable(group(p,r=>r.payerType||"Unknown"),"Payer")}
function renderDelivery(){let c=calc(),el=$("view-delivery");if(!el)return;el.innerHTML=`<div class="grid">${metric("Deliveries",fmt(c.deliveries),"completed")}${metric("First Attempt %",pct(c.firstDelivery),"first attempt")}${metric("Failure Rate",pct(c.deliveries?c.deliveryFailures/c.deliveries*100:0),"failed")}${metric("Cost / Success",money((c.deliveries-c.deliveryFailures)?c.delivery/(c.deliveries-c.deliveryFailures):0),"delivery cost per success")}</div>`}
function renderHistory(){let d=db().manual,dates=Object.keys(d).sort(),el=$("view-history")||$("view-settings");if(!$("view-history"))return;el.innerHTML='<h2>Saved Manual Days</h2>'+table(["Date","Scripts","Revenue","COGS","GP","Notes"],dates.map(dt=>[esc(dt),fmt(d[dt].scriptsFilled),money(d[dt].revenue),money(d[dt].cogs),money(n(d[dt].revenue)-n(d[dt].cogs)),esc(d[dt].notes||"")]))+`<button class="btn blue" onclick="exportHistory()">Export History CSV</button>`}
function renderMeeting(){let c=calc();$("view-meeting").innerHTML=`<div class="card"><h2>Weekly Operating Meeting</h2><p><b>1. What came in?</b> ${fmt(c.scriptsReceived)} scripts, ${fmt(c.newPatients)} new patients, ${fmt(c.newDoctors)} new doctors.</p><p><b>2. What got out?</b> ${fmt(c.scriptsFilled)} filled, ${pct(c.fill)} fill rate.</p><p><b>3. What leaked?</b> ${fmt(c.scriptsReversed+c.scriptsAbandoned)} reversed/abandoned, ${fmt(c.paBacklog)} PA backlog, ${fmt(c.dsOhRisk)} DSOH risk.</p><p><b>4. What did it cost?</b> ${money(c.costRx)} cost/Rx, ${ratio(c.costGp)} cost/$GP.</p><p><b>5. What is true?</b> GP ${money(c.gp)}, EBITDA proxy ${money(c.ebitda)}, low cash ${money(cashLow())}.</p></div><h2>Agenda From Alerts</h2><div class="grid3">${alerts(c).map(a=>`<div class="card"><span class="pill">${esc(a[0])}</span><p class="${a[2]}" style="font-weight:900">${esc(a[1])}</p></div>`).join("")}</div>`}
function renderSettings(){let t=db().targets;$("view-settings").innerHTML=`<h2>Targets</h2><div class="card grid3">${Object.entries(t).map(([k,v])=>`<div><label>${esc(label(k))}</label><input id="t_${k}" value="${esc(v)}"></div>`).join("")}</div><button class="btn primary" onclick="saveTargets()">Save Targets</button><h2>Controls</h2><button class="btn red" onclick="resetApp()">Reset All Local Data</button>`}
function saveTargets(){let d=db();Object.keys(d.targets).forEach(k=>d.targets[k]=n($("t_"+k).value));saveDb(d);render();toast("Targets saved")}
function tmpl(t){let x={pioneer:'date,rxNumber,patientId,doctor,location,channel,status,revenue,cogs,grossProfit,timeToStartHours,adherencePct,payer,drugName,ndc,paStatus,rejectCode,payerType,drugClass,isFirstFill,isSecondFill,dsOhDays\n2026-05-10,RX1,P1,Doctor One,Location One,Doctor Practice,Filled,125,82,43,18,92,Payer A,Drug A,000,Approved,,Commercial,Cardiology,yes,no,12\n',cash:'date,account,description,amount,category,location,team\n2026-05-10,Account One,Sample Expense,-100,labor,Location One,Ops\n',intacct:'date,location,account,accountType,amount,department,vendor,customer\n2026-05-10,Location One,Revenue,revenue,50000,Store,,\n2026-05-10,Location One,Drug Cost,cogs,35000,Store,Vendor,\n',powerbi:'date,location,channel,doctor,enterpriseAccount,patients,scriptsReceived,scriptsFilled,revenue,cogs,grossProfit,adherencePct,fillRatePct\n2026-05-10,Location One,Doctor Practice,Doctor One,Account One,250,330,300,42000,30000,12000,88,91\n'}[t];download(t+'_template.csv',x)}
function download(nm,txt){let b=new Blob([txt],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=nm;a.click()}
function backup(){download('onpoint_dashboard_backup.json',JSON.stringify(db(),null,2))}
async function restore(e){let f=e.target.files[0];if(!f)return;saveDb(JSON.parse(await f.text()));toast('Restored');render()}
function exportHistory(){let d=db().manual,csv='date,scriptsReceived,scriptsFilled,revenue,cogs,gp,adherence,notes\n';Object.keys(d).sort().forEach(dt=>{let r=d[dt];csv+=[dt,r.scriptsReceived,r.scriptsFilled,r.revenue,r.cogs,n(r.revenue)-n(r.cogs),r.adherence,r.notes].map(csvSafe).join(',')+'\n'});download('onpoint_history.csv',csv)}
function resetApp(){if(confirm('Reset all dashboard data?')){localStorage.removeItem(KEY);toast('Reset');render()}}
const NAV=[["command","Command Center"],["daily","Daily Entry"],["imports","Import Center"],["ledgers","Finance + Forecast"],["pa","PA Intelligence"],["retention","Retention + DSOH"],["teams","Teams + OKRs"],["channels","Channels"],["locations","Locations"],["doctors","Doctors"],["enterprise","Enterprise"],["drugs","Drug Mix"],["delivery","Delivery"],["history","History"],["meeting","Meeting Mode"],["settings","Settings"]];
function navInit(){let nav=$("nav");nav.innerHTML=NAV.map(([id,n])=>`<button data-v="${id}">${n}</button>`).join("");nav.querySelectorAll('button').forEach(b=>b.onclick=()=>show(b.dataset.v));nav.querySelector('[data-v=command]').classList.add('active')}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));let el=$("view-"+id);if(el)el.classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===id));$("pageTitle").textContent=NAV.find(x=>x[0]===id)?.[1]||'Dashboard';render()}
function render(){renderCommand();renderDaily();renderImports();renderFinance();renderPA();renderRetention();renderTeams();renderChannels();renderLocations();renderDoctors();renderEnterprise();renderDrugs();renderDelivery();renderHistory();renderMeeting();renderSettings();storage()}
async function authInit(){let a=JSON.parse(localStorage.getItem(AUTH)||'{}');if(sessionStorage.getItem(AUTH)==='ok')return openApp();$("authView").classList.remove('hidden');if(!a.hash){$("setupBlock").classList.remove('hidden')}else{$("loginBlock").classList.remove('hidden');$("authCopy").textContent='Enter password to unlock.'}}
async function setPassword(){let p=$("newPassword").value,c=$("confirmPassword").value;if(p.length<6)return $("authMessage").textContent='Use at least 6 characters.';if(p!==c)return $("authMessage").textContent='Passwords do not match.';localStorage.setItem(AUTH,JSON.stringify({hash:await sha(p)}));sessionStorage.setItem(AUTH,'ok');openApp()}
async function unlock(){let a=JSON.parse(localStorage.getItem(AUTH)||'{}');if(await sha($("password").value)===a.hash){sessionStorage.setItem(AUTH,'ok');openApp()}else $("authMessage").textContent='Wrong password.'}
function openApp(){$("authView").classList.add('hidden');$("appView").classList.remove('hidden');if(openApp.done)return;openApp.done=true;$("rangeStart").value=addDays(today(),-30);$("rangeEnd").value=today();navInit();$("saveBtn").onclick=()=>{saveDb(db());toast('Saved')};$("lockBtn").onclick=()=>{sessionStorage.removeItem(AUTH);location.reload()};$("rangeStart").onchange=render;$("rangeEnd").onchange=render;$("dataMode").onchange=render;if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render()}
$("setPasswordBtn").onclick=setPassword;$("unlockBtn").onclick=unlock;authInit();