/* OnPoint Growth Layer: scenario planning, cohorts/LTV, playbooks, team heatmap, mobile CEO mode. */
(function(){
  'use strict';
  const BASE_KEY='opdash.pages.v1';
  const OPS_KEY='opdash.opslayer.v1';
  const GROWTH_KEY='opdash.growthlayer.v1';
  const $=id=>document.getElementById(id);
  const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const n=x=>Number(x)||0;
  const money=x=>'$'+Math.round(n(x)).toLocaleString();
  const num=x=>Math.round(n(x)).toLocaleString();
  const pct=x=>isFinite(x)?Number(x).toFixed(1)+'%':'0.0%';
  const today=()=>new Date().toISOString().slice(0,10);

  function base(){try{return JSON.parse(localStorage.getItem(BASE_KEY))||{manual:{},imports:{}}}catch(e){return{manual:{},imports:{}}}}
  function ops(){try{return JSON.parse(localStorage.getItem(OPS_KEY))||{employees:[],actions:[],pipeline:[],budgets:[]}}catch(e){return{employees:[],actions:[],pipeline:[],budgets:[]}}}
  function seed(){return{scenarios:[],cohorts:[],playbooks:defaultPlaybooks(),roleMode:'CEO'}}
  function state(){try{return JSON.parse(localStorage.getItem(GROWTH_KEY))||seed()}catch(e){return seed()}}
  function save(s){localStorage.setItem(GROWTH_KEY,JSON.stringify(s))}
  function safeCalc(){try{return typeof calc==='function'?calc():{}}catch(e){return{}}}
  function toast(msg){try{window.toast?window.toast(msg):alert(msg)}catch(e){}}

  const tabs=[['mobileceo','CEO Mobile'],['scenario','Scenario'],['cohorts','Cohorts'],['playbooks','Playbooks'],['heatmap','Team Heatmap']];
  function ensureViews(){const main=document.querySelector('.main');if(!main)return;tabs.forEach(([id])=>{if(!$('view-'+id)){const s=document.createElement('section');s.id='view-'+id;s.className='view';main.appendChild(s)}})}
  function ensureTabs(){const nav=$('nav');if(!nav)return;tabs.forEach(([id,label])=>{if(nav.querySelector(`[data-v="${id}"], [data-view="${id}"]`))return;const b=document.createElement('button');b.dataset.v=id;b.textContent=label;b.onclick=()=>show(id);nav.appendChild(b)})}
  function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-'+id)?.classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',(b.dataset.v||b.dataset.view)===id));const title=$('pageTitle');if(title)title.textContent=tabs.find(t=>t[0]===id)?.[1]||id;render();window.scrollTo({top:0,behavior:'smooth'})}
  function table(headers,rows){if(!rows.length)return`<div class="empty-state"><b>No data yet</b>Add rows to use this tool.</div>`;return`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function metric(label,value,sub='',cls=''){return`<div class="mini-card"><div class="label">${esc(label)}</div><div class="value ${cls}">${esc(value)}</div><div class="sub">${esc(sub)}</div></div>`}
  function input(id,val,left=false,type='number'){return`<input ${left?'class="left"':''} id="${esc(id)}" type="${type}" value="${esc(val??'')}">`}
  function select(id,opts,val){return`<select id="${esc(id)}">${opts.map(o=>`<option ${o===val?'selected':''}>${esc(o)}</option>`).join('')}</select>`}
  function badge(text,type){return`<span class="badge ${type||'blue'}">${esc(text)}</span>`}

  function renderMobileCEO(){const el=$('view-mobileceo');if(!el)return;const c=safeCalc(),o=ops();const actions=(o.actions||[]).filter(a=>a.status!=='Done').slice(0,5);el.innerHTML=`<div class="feature-hero"><h2>CEO Mobile Mode</h2><p>The no-clutter version: cash, GP, scripts, fill rate, breakeven, PA, DSOH, and top actions.</p></div><div class="kpi-band">${metric('Cash',money(c.cash),'current')}${metric('GP',money(c.gp),'selected period')}${metric('Filled',num(c.scriptsFilled),'scripts out')}${metric('Fill Rate',pct(c.fill||c.fillRate),'execution',(c.fill||c.fillRate)>=90?'good':'bad')}${metric('Breakeven',num(c.breakeven||c.breakevenRx),'scripts needed')}</div><div class="kpi-band">${metric('PA Backlog',num(c.paBacklog),'invisible leakage',c.paBacklog?'bad':'good')}${metric('DSOH Risk',num(c.dsOhRisk),'patients near gap',c.dsOhRisk?'warn':'good')}${metric('GP/Rx',money(c.gpRx),'script value')}${metric('Cost/Rx',money(c.costRx),'efficiency',c.costRx<=10?'good':'warn')}${metric('Open Actions',num(actions.length),'top visible')}</div><h2>Top Actions</h2><div class="action-list">${actions.length?actions.map(a=>`<div class="action-item ${a.priority==='Critical'||a.priority==='High'?'red':a.priority==='Medium'?'amber':'green'}"><div class="action-title">${esc(a.title)} ${badge(a.priority||'Medium',a.priority==='Critical'||a.priority==='High'?'bad':a.priority==='Medium'?'warn':'blue')}</div><div class="action-copy">Owner: ${esc(a.owner||'Unassigned')} | Team: ${esc(a.team||'')} | Due: ${esc(a.due||'')}</div></div>`).join(''):'<div class="empty-state"><b>No open actions</b>Create actions from the Actions tab or Suggested Actions.</div>'}</div>`}

  function renderScenario(){const el=$('view-scenario');if(!el)return;const c=safeCalc(),s=state();const rows=s.scenarios.map((r,i)=>{const days=n(r.days)||30,rev=n(r.scriptsPerDay)*days*n(r.revenueRx),gp=n(r.scriptsPerDay)*days*n(r.gpRx),varCost=n(r.scriptsPerDay)*days*n(r.costRx),profit=gp-varCost-n(r.fixedCost);return[esc(r.name),num(r.scriptsPerDay),money(r.revenueRx),money(r.gpRx),money(r.costRx),money(r.fixedCost),money(rev),money(gp),money(profit),`<button class="btn red" onclick="GrowthLayer.delScenario(${i})">Delete</button>`]});
    el.innerHTML=`<div class="feature-hero"><h2>Scenario Planner</h2><p>Model scripts/day, revenue/Rx, GP/Rx, cost/Rx, and fixed cost. This is the boring but useful math for operating decisions.</p></div><div class="kpi-band">${metric('Current GP/Rx',money(c.gpRx),'from dashboard')}${metric('Current Cost/Rx',money(c.costRx),'from dashboard')}${metric('Current Fill Rate',pct(c.fill||c.fillRate),'from dashboard')}${metric('Current Scripts',num(c.scriptsFilled),'selected period')}${metric('Breakeven',num(c.breakeven||c.breakevenRx),'current model')}</div><h2>Saved Scenarios</h2>${table(['Name','Scripts/Day','Revenue/Rx','GP/Rx','Cost/Rx','Fixed Cost','Revenue','GP','Contribution',''],rows)}<h2>Add Scenario</h2><div class="card feature-grid form-table"><div><label>Name</label>${input('sc_name','Base Case',true,'text')}</div><div><label>Days</label>${input('sc_days',30)}</div><div><label>Scripts / Day</label>${input('sc_scripts',100)}</div><div><label>Revenue / Rx</label>${input('sc_rev',250)}</div><div><label>GP / Rx</label>${input('sc_gp',40)}</div><div><label>Cost / Rx</label>${input('sc_cost',10)}</div><div><label>Fixed Cost</label>${input('sc_fixed',50000)}</div></div><button class="btn primary" onclick="GrowthLayer.addScenario()">Add Scenario</button>`}

  function renderCohorts(){const el=$('view-cohorts');if(!el)return;const s=state();const rows=s.cohorts.map((r,i)=>{const retained=n(r.starts)*n(r.retention)/100, fills=retained*n(r.fillsPerYear), ltv=n(r.gpRx)*n(r.fillsPerYear)*n(r.retention)/100, annualGp=fills*n(r.gpRx);return[esc(r.therapy),num(r.starts),pct(r.retention),num(r.fillsPerYear),money(r.gpRx),money(ltv),money(annualGp),`<button class="btn red" onclick="GrowthLayer.delCohort(${i})">Delete</button>`]});const totalGp=s.cohorts.reduce((a,r)=>a+(n(r.starts)*n(r.retention)/100*n(r.fillsPerYear)*n(r.gpRx)),0);
    el.innerHTML=`<div class="feature-hero"><h2>Cohort & Patient LTV</h2><p>Estimate what a retained patient is worth by therapy class. This changes what you can spend on acquisition, adherence, and service.</p></div><div class="kpi-band">${metric('Cohorts',num(s.cohorts.length),'therapy models')}${metric('Modeled Annual GP',money(totalGp),'from cohorts')}${metric('Avg LTV',money(s.cohorts.length?totalGp/s.cohorts.reduce((a,r)=>a+n(r.starts),0):0),'per started patient')}${metric('Best Class',bestCohort(s.cohorts),'highest GP opportunity')}${metric('Use Case','Acquisition CAC','what can we spend?')}</div><h2>Cohorts</h2>${table(['Therapy Class','Starts','Retention','Fills/Yr','GP/Rx','Patient LTV','Annual GP',''],rows)}<h2>Add Cohort</h2><div class="card feature-grid form-table"><div><label>Therapy Class</label>${input('co_therapy','Cardiology',true,'text')}</div><div><label>Starts</label>${input('co_starts',100)}</div><div><label>Retention %</label>${input('co_retention',70)}</div><div><label>Fills / Year</label>${input('co_fills',10)}</div><div><label>GP / Rx</label>${input('co_gp',40)}</div></div><button class="btn primary" onclick="GrowthLayer.addCohort()">Add Cohort</button>`}
  function bestCohort(rows){if(!rows.length)return'None yet';let best=rows.slice().sort((a,b)=>(n(b.starts)*n(b.retention)*n(b.fillsPerYear)*n(b.gpRx))-(n(a.starts)*n(a.retention)*n(a.fillsPerYear)*n(a.gpRx)))[0];return best?best.therapy:'None'}

  function defaultPlaybooks(){return[
    {trigger:'PA backlog high',owner:'Pharmacy Ops',cadence:'Daily',steps:'Pull oldest PA queue, sort by payer, assign top 10 to owners, review denial codes, escalate doctor-needed items.'},
    {trigger:'GP/Rx down',owner:'Finance',cadence:'Weekly',steps:'Review payer mix, top drugs by GP, DIR exposure, rejected claims, and low-margin scripts.'},
    {trigger:'Cost/Rx up',owner:'Pharmacy Ops',cadence:'Weekly',steps:'Review staffing, labor hours per script, delivery cost per success, and low-volume locations.'},
    {trigger:'Doctor silent 30+ days',owner:'Sales',cadence:'Weekly',steps:'Call doctor, review recent service issues, share value data, ask for next 3 appropriate patients.'},
    {trigger:'DSOH risk rising',owner:'Pharmacy Ops',cadence:'Daily',steps:'Generate patient risk list, outreach before gap, document unreachable patients, escalate financial assistance needs.'}
  ]}
  function renderPlaybooks(){const el=$('view-playbooks');if(!el)return;const s=state();const rows=(s.playbooks||[]).map((p,i)=>[esc(p.trigger),esc(p.owner),esc(p.cadence),esc(p.steps),`<button class="btn red" onclick="GrowthLayer.delPlaybook(${i})">Delete</button>`]);el.innerHTML=`<div class="feature-hero"><h2>Operating Playbooks</h2><p>When a metric turns red, the team should not invent a response from scratch. These are the default plays.</p></div>${table(['Trigger','Owner','Cadence','Steps',''],rows)}<h2>Add Playbook</h2><div class="card feature-grid form-table"><div><label>Trigger</label>${input('pb_trigger','Fill rate below target',true,'text')}</div><div><label>Owner</label>${select('pb_owner',['Sales','Enterprise','Pharmacy Ops','Technology','Finance','Executive'],'Pharmacy Ops')}</div><div><label>Cadence</label>${select('pb_cadence',['Daily','Weekly','Monthly','As Needed'],'Daily')}</div><div style="grid-column:1/-1"><label>Steps</label><textarea id="pb_steps" class="left">Define the steps...</textarea></div></div><button class="btn primary" onclick="GrowthLayer.addPlaybook()">Add Playbook</button>`}

  function renderHeatmap(){const el=$('view-heatmap');if(!el)return;const o=ops(),teams=['Executive','Sales','Enterprise','Pharmacy Ops','Technology','Finance'];const rows=teams.map(t=>{const acts=(o.actions||[]).filter(a=>a.team===t&&a.status!=='Done'),critical=acts.filter(a=>a.priority==='Critical'||a.priority==='High').length,blocked=acts.filter(a=>a.status==='Blocked').length,owned=acts.filter(a=>a.owner&&a.owner!=='Unassigned').length;return[esc(t),num(acts.length),num(critical),num(blocked),pct(acts.length?owned/acts.length*100:100),heatBadge(acts.length,critical,blocked)]});const people=(o.employees||[]).map(e=>{const acts=(o.actions||[]).filter(a=>a.owner===e.name&&a.status!=='Done');return[esc(e.name),esc(e.role),esc(e.team),num(acts.length),num(acts.filter(a=>a.priority==='Critical'||a.priority==='High').length),acts.length>5?badge('Overloaded','bad'):acts.length>2?badge('Busy','warn'):badge('OK','good')]});
    el.innerHTML=`<div class="feature-hero"><h2>Team Accountability Heatmap</h2><p>See where work is piling up, who owns it, and which teams are blocked or overloaded.</p></div><h2>Team Load</h2>${table(['Team','Open Actions','Critical/High','Blocked','Owned %','Status'],rows)}<h2>Employee Load</h2>${table(['Employee','Role','Team','Open Actions','Critical/High','Status'],people)}`}
  function heatBadge(open,critical,blocked){if(blocked||critical>2)return badge('Red','bad');if(open>5||critical>0)return badge('Watch','warn');return badge('Good','good')}

  function render(){ensureViews();ensureTabs();renderMobileCEO();renderScenario();renderCohorts();renderPlaybooks();renderHeatmap()}
  window.GrowthLayer={render,show,addScenario(){let s=state();s.scenarios.push({name:$('sc_name')?.value||'Scenario',days:$('sc_days')?.value||30,scriptsPerDay:$('sc_scripts')?.value||0,revenueRx:$('sc_rev')?.value||0,gpRx:$('sc_gp')?.value||0,costRx:$('sc_cost')?.value||0,fixedCost:$('sc_fixed')?.value||0});save(s);toast('Scenario added');render()},delScenario(i){let s=state();s.scenarios.splice(i,1);save(s);render()},addCohort(){let s=state();s.cohorts.push({therapy:$('co_therapy')?.value||'Therapy',starts:$('co_starts')?.value||0,retention:$('co_retention')?.value||0,fillsPerYear:$('co_fills')?.value||0,gpRx:$('co_gp')?.value||0});save(s);toast('Cohort added');render()},delCohort(i){let s=state();s.cohorts.splice(i,1);save(s);render()},addPlaybook(){let s=state();s.playbooks=s.playbooks||defaultPlaybooks();s.playbooks.push({trigger:$('pb_trigger')?.value||'',owner:$('pb_owner')?.value||'',cadence:$('pb_cadence')?.value||'',steps:$('pb_steps')?.value||''});save(s);toast('Playbook added');render()},delPlaybook(i){let s=state();s.playbooks.splice(i,1);save(s);render()}};
  const old=window.render;if(typeof old==='function'){window.render=function(){const out=old.apply(this,arguments);setTimeout(render,0);return out}}
  document.addEventListener('DOMContentLoaded',()=>setTimeout(render,1300));
  setInterval(render,6000);
})();
