/* OnPoint Operating Layer: people, roles, actions, budget, pipeline, QA, and suggested actions. */
(function(){
  'use strict';
  const KEY='opdash.opslayer.v1';
  const $=id=>document.getElementById(id);
  const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const n=x=>Number(x)||0;
  const money=x=>'$'+Math.round(n(x)).toLocaleString();
  const num=x=>Math.round(n(x)).toLocaleString();
  const pct=x=>isFinite(x)?Number(x).toFixed(1)+'%':'0.0%';
  const today=()=>new Date().toISOString().slice(0,10);
  const roles=['CEO','Sales','Enterprise','Pharmacy Ops','Technology','Finance','Location Manager','Pharmacist','Technician','Delivery','Accounting','Admin'];
  const teams=['Executive','Sales','Enterprise','Pharmacy Ops','Technology','Finance'];

  function seed(){return{employees:[],actions:[],budgets:[],pipeline:[],settings:{autoLockMinutes:15,safetyAccepted:false}}}
  function state(){try{return JSON.parse(localStorage.getItem(KEY))||seed()}catch(e){return seed()}}
  function save(s){localStorage.setItem(KEY,JSON.stringify(s));}
  function safeCalc(){try{return typeof calc==='function'?calc():{}}catch(e){return{}}}
  function toast(msg){try{window.toast?window.toast(msg):alert(msg)}catch(e){}}
  function input(id,val,left=false,type='text'){return`<input ${left?'class="left"':''} id="${esc(id)}" type="${type}" value="${esc(val??'')}">`}
  function select(id,opts,val){return`<select id="${esc(id)}">${opts.map(o=>`<option ${o===val?'selected':''}>${esc(o)}</option>`).join('')}</select>`}
  function table(headers,rows){if(!rows.length)return`<div class="empty-state"><b>No rows yet</b>Add a row below.</div>`;return`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function metric(label,value,sub='',cls=''){return`<div class="mini-card"><div class="label">${esc(label)}</div><div class="value ${cls}">${esc(value)}</div><div class="sub">${esc(sub)}</div></div>`}
  function badge(text,type){return`<span class="badge ${type||'blue'}">${esc(text)}</span>`}

  const tabs=[['people','People'],['actions','Actions'],['budget','Budget'],['pipeline','Pipeline'],['worklists','Worklists'],['dataqa','Data QA']];
  function ensureViews(){const main=document.querySelector('.main');if(!main)return;tabs.forEach(([id])=>{if(!$('view-'+id)){let s=document.createElement('section');s.id='view-'+id;s.className='view';main.appendChild(s)}})}
  function ensureTabs(){const nav=$('nav');if(!nav)return;tabs.forEach(([id,label])=>{if(nav.querySelector(`[data-v="${id}"], [data-view="${id}"]`))return;let b=document.createElement('button');b.dataset.v=id;b.textContent=label;b.onclick=()=>show(id);nav.appendChild(b)})}
  function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));let el=$('view-'+id);if(el)el.classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',(b.dataset.v||b.dataset.view)===id));let title=$('pageTitle');if(title)title.textContent=tabs.find(t=>t[0]===id)?.[1]||id;render();window.scrollTo({top:0,behavior:'smooth'})}

  function ownerOptions(){let s=state();return ['Unassigned'].concat(s.employees.filter(e=>e.active!=='No').map(e=>e.name||'Unnamed'))}

  function suggestedActions(){let c=safeCalc(),out=[];
    const gpRx=n(c.gpRx),costRx=n(c.costRx),fill=n(c.fill||c.fillRate),adherence=n(c.adherence),pa=n(c.paBacklog),ds=n(c.dsOhRisk),cash=n(c.cash),ap=n(c.ap||c.apDue),debt=n(c.debt||c.debtDue),reversed=n(c.scriptsReversed),abandoned=n(c.scriptsAbandoned);
    if(pa>0)out.push({title:'Clear PA backlog',team:'Pharmacy Ops',role:'Pharmacist',priority:'High',metric:'PA Backlog',why:`${num(pa)} scripts are waiting on PA. Pull oldest 10, group by payer, assign owners today.`});
    if(fill<90)out.push({title:'Diagnose fill-rate gap',team:'Pharmacy Ops',role:'Pharmacist',priority:'High',metric:'Fill Rate',why:`Fill rate is ${pct(fill)}. Separate PA, payer rejection, patient contact, inventory, and doctor clarification causes.`});
    if(ds>0)out.push({title:'Call DSOH risk patients',team:'Pharmacy Ops',role:'Technician',priority:'High',metric:'DSOH Risk',why:`${num(ds)} patients are near therapy gap. Contact before adherence drops.`});
    if(gpRx>0&&gpRx<40)out.push({title:'Review payer and drug mix',team:'Finance',role:'Finance',priority:'Medium',metric:'GP/Rx',why:`GP/Rx is ${money(gpRx)}. Check payer mix, DIR exposure, top drugs by GP, and low-margin claims.`});
    if(costRx>10)out.push({title:'Reduce cost per script',team:'Pharmacy Ops',role:'Location Manager',priority:'Medium',metric:'Cost/Rx',why:`Cost/Rx is ${money(costRx)}. Review staffing, delivery failures, low-volume locations, and workflow waste.`});
    if(cash<(ap+debt)&&ap+debt>0)out.push({title:'Build cash triage plan',team:'Finance',role:'Finance',priority:'Critical',metric:'Cash',why:`Cash is below AP + debt due. Prioritize vendor payments, PBM receivables, ordering needs, and payroll.`});
    if((reversed+abandoned)>0)out.push({title:'Recover script leakage',team:'Pharmacy Ops',role:'Technician',priority:'Medium',metric:'Leakage',why:`${num(reversed+abandoned)} scripts reversed or abandoned. Identify payer vs patient vs inventory causes.`});
    if(adherence>0&&adherence<85)out.push({title:'Run adherence rescue list',team:'Pharmacy Ops',role:'Technician',priority:'Medium',metric:'Adherence',why:`Adherence is ${pct(adherence)}. Focus on chronic patients with refill gaps.`});
    if(!out.length)out.push({title:'No red flag actions',team:'Executive',role:'CEO',priority:'Low',metric:'General',why:'No major triggers from current data. Pick one bottleneck to improve before it becomes a red flag.'});
    return out;
  }

  function renderPeople(){let s=state(),el=$('view-people');if(!el)return;let rows=s.employees.map((e,i)=>[esc(e.name),esc(e.role),esc(e.team),esc(e.email||''),esc(e.tags||''),e.active==='No'?badge('Inactive','warn'):badge('Active','good'),`<button class="btn red" onclick="OpsLayer.delEmployee(${i})">Delete</button>`]);
    el.innerHTML=`<div class="feature-hero"><h2>People, Roles & Tags</h2><p>Add employees, assign roles and teams, then tag them to locations, channels, metrics, doctors, or enterprise accounts. Action items can be assigned to people or roles.</p></div><div class="kpi-band">${metric('Employees',num(s.employees.length),'people in system')}${metric('Active',num(s.employees.filter(e=>e.active!=='No').length),'available owners')}${metric('Roles',num(new Set(s.employees.map(e=>e.role)).size),'roles represented')}${metric('Teams',num(new Set(s.employees.map(e=>e.team)).size),'teams represented')}${metric('Open Actions',num(s.actions.filter(a=>a.status!=='Done').length),'assigned work')}</div><h2>Employee Directory</h2>${table(['Name','Role','Team','Email','Tags','Status',''],rows)}<h2>Add Employee</h2><div class="card feature-grid form-table"><div><label>Name</label>${input('emp_name','',true)}</div><div><label>Role</label>${select('emp_role',roles,'Pharmacist')}</div><div><label>Team</label>${select('emp_team',teams,'Pharmacy Ops')}</div><div><label>Email</label>${input('emp_email','',true,'email')}</div><div><label>Tags</label>${input('emp_tags','Flushing, PA, adherence',true)}</div><div><label>Active</label>${select('emp_active',['Yes','No'],'Yes')}</div></div><button class="btn primary" onclick="OpsLayer.addEmployee()">Add Employee</button>`}

  function renderActions(){let s=state(),el=$('view-actions');if(!el)return;let sug=suggestedActions();let rows=s.actions.map((a,i)=>[priorityBadge(a.priority),esc(a.title),esc(a.owner||'Unassigned'),esc(a.team),esc(a.metric),esc(a.due||''),statusBadge(a.status),`<button class="btn" onclick="OpsLayer.doneAction(${i})">Done</button> <button class="btn red" onclick="OpsLayer.delAction(${i})">Delete</button>`]);
    el.innerHTML=`<div class="feature-hero"><h2>Suggested Actions & Accountability</h2><p>The dashboard should not only show numbers. It should tell the team what to do, who owns it, and when it is due.</p></div><div class="kpi-band">${metric('Open Actions',num(s.actions.filter(a=>a.status!=='Done').length),'not done')}${metric('Critical',num(s.actions.filter(a=>a.priority==='Critical'&&a.status!=='Done').length),'act today')}${metric('High',num(s.actions.filter(a=>a.priority==='High'&&a.status!=='Done').length),'urgent')}${metric('Unassigned',num(s.actions.filter(a=>(!a.owner||a.owner==='Unassigned')&&a.status!=='Done').length),'needs owner')}${metric('Suggestions',num(sug.length),'from dashboard')}</div><h2>Suggested Actions</h2><div class="action-list">${sug.map((a,idx)=>`<div class="action-item ${a.priority==='Critical'?'red':a.priority==='High'?'red':a.priority==='Medium'?'amber':'green'}"><div class="action-title">${esc(a.title)} ${priorityBadge(a.priority)}</div><div class="action-copy">${esc(a.why)}</div><div style="margin-top:8px"><button class="btn primary" onclick="OpsLayer.acceptSuggestion(${idx})">Create Action</button></div></div>`).join('')}</div><h2>Action Register</h2>${table(['Priority','Action','Owner','Team','Metric','Due','Status',''],rows)}<h2>Add Action</h2><div class="card feature-grid form-table"><div><label>Title</label>${input('act_title','',true)}</div><div><label>Owner</label>${select('act_owner',ownerOptions(),'Unassigned')}</div><div><label>Team</label>${select('act_team',teams,'Pharmacy Ops')}</div><div><label>Metric</label>${input('act_metric','PA Backlog',true)}</div><div><label>Priority</label>${select('act_priority',['Critical','High','Medium','Low'],'Medium')}</div><div><label>Due</label>${input('act_due',today(),false,'date')}</div><div><label>Status</label>${select('act_status',['Open','In Progress','Blocked','Done'],'Open')}</div><div><label>Tags</label>${input('act_tags','',true)}</div></div><button class="btn primary" onclick="OpsLayer.addAction()">Add Action</button>`}

  function priorityBadge(p){return badge(p||'Medium',p==='Critical'||p==='High'?'bad':p==='Medium'?'warn':'blue')}
  function statusBadge(s){return badge(s||'Open',s==='Done'?'good':s==='Blocked'?'bad':s==='In Progress'?'warn':'blue')}

  function renderBudget(){let s=state(),c=safeCalc(),el=$('view-budget');if(!el)return;let totals=s.budgets.reduce((a,r)=>{a.rev+=n(r.revenueBudget);a.gp+=n(r.gpBudget);a.opex+=n(r.opexBudget);a.scripts+=n(r.scriptsBudget);return a},{rev:0,gp:0,opex:0,scripts:0});let opex=n(c.ops)+n(c.salesCost)+n(c.techCost)+n(c.enterpriseCost)+n(c.corpCost);let rows=s.budgets.map((r,i)=>[esc(r.name),esc(r.type),esc(r.period),money(r.revenueBudget),money(r.gpBudget),money(r.opexBudget),num(r.scriptsBudget),`<button class="btn red" onclick="OpsLayer.delBudget(${i})">Delete</button>`]);
    el.innerHTML=`<div class="feature-hero"><h2>Budget vs Actual</h2><p>Budget by location, team, channel, or enterprise account. Compare actual revenue, GP, opex, and scripts against plan.</p></div><div class="kpi-band">${metric('Budget Revenue',money(totals.rev),'planned')}${metric('Actual Revenue',money(c.revenue),'dashboard')}${metric('Revenue Variance',money(n(c.revenue)-totals.rev),'actual minus plan',n(c.revenue)>=totals.rev?'good':'bad')}${metric('GP Variance',money(n(c.gp)-totals.gp),'actual minus plan',n(c.gp)>=totals.gp?'good':'bad')}${metric('Opex Variance',money(opex-totals.opex),'actual minus plan',opex<=totals.opex?'good':'bad')}</div><h2>Budget Rows</h2>${table(['Name','Type','Period','Revenue','GP','Opex','Scripts',''],rows)}<h2>Add Budget</h2><div class="card feature-grid form-table"><div><label>Name</label>${input('bud_name','Location 1',true)}</div><div><label>Type</label>${select('bud_type',['Location','Team','Channel','Enterprise'],'Location')}</div><div><label>Period</label>${input('bud_period',today().slice(0,7),true,'month')}</div><div><label>Revenue</label>${input('bud_rev',0,false,'number')}</div><div><label>GP</label>${input('bud_gp',0,false,'number')}</div><div><label>Opex</label>${input('bud_opex',0,false,'number')}</div><div><label>Scripts</label>${input('bud_scripts',0,false,'number')}</div></div><button class="btn primary" onclick="OpsLayer.addBudget()">Add Budget</button><h2>Breakeven Sensitivity</h2>${breakevenTable(c)}`}

  function breakevenTable(c){let gp=Math.max(n(c.gpRx),1),cost=n(c.total),gps=[gp*.75,gp,gp*1.25,gp*1.5],costs=[cost*.85,cost,cost*1.15];return table(['Cost Level',...gps.map(x=>'GP/Rx '+money(x))],costs.map(co=>[money(co),...gps.map(g=>num(Math.ceil(co/g)))]))}

  function renderPipeline(){let s=state(),el=$('view-pipeline');if(!el)return;let weighted=s.pipeline.reduce((a,r)=>a+n(r.expectedGp)*n(r.probability)/100,0),rows=s.pipeline.map((r,i)=>[esc(r.name),esc(r.type),esc(r.stage),money(r.expectedGp),pct(r.probability),money(n(r.expectedGp)*n(r.probability)/100),esc(r.owner||''),esc(r.nextStep||''),`<button class="btn red" onclick="OpsLayer.delPipeline(${i})">Delete</button>`]);
    el.innerHTML=`<div class="feature-hero"><h2>Weighted Pipeline</h2><p>Probability-adjusted GP from doctors, medical groups, pharma, payors, and other opportunities.</p></div><div class="kpi-band">${metric('Opportunities',num(s.pipeline.length),'pipeline rows')}${metric('Weighted GP',money(weighted),'probability adjusted')}${metric('Avg Weighted GP',money(s.pipeline.length?weighted/s.pipeline.length:0),'per opportunity')}${metric('Won GP',money(s.pipeline.filter(r=>r.stage==='Won').reduce((a,r)=>a+n(r.expectedGp),0)),'closed won')}${metric('Unowned',num(s.pipeline.filter(r=>!r.owner||r.owner==='Unassigned').length),'needs owner')}</div><h2>Pipeline</h2>${table(['Name','Type','Stage','Expected GP','Probability','Weighted GP','Owner','Next Step',''],rows)}<h2>Add Opportunity</h2><div class="card feature-grid form-table"><div><label>Name</label>${input('pipe_name','',true)}</div><div><label>Type</label>${select('pipe_type',['Doctor','Medical Group','Pharma','Payor','Facility','Other'],'Doctor')}</div><div><label>Stage</label>${select('pipe_stage',['Prospect','Meeting','Proposal','Active Pilot','Won','Lost'],'Prospect')}</div><div><label>Expected GP</label>${input('pipe_gp',0,false,'number')}</div><div><label>Probability %</label>${input('pipe_prob',25,false,'number')}</div><div><label>Owner</label>${select('pipe_owner',ownerOptions(),'Unassigned')}</div><div><label>Next Step</label>${input('pipe_next','Schedule follow-up',true)}</div></div><button class="btn primary" onclick="OpsLayer.addPipeline()">Add Opportunity</button>`}

  function renderWorklists(){let c=safeCalc(),el=$('view-worklists');if(!el)return;let acts=suggestedActions();el.innerHTML=`<div class="feature-hero"><h2>Daily Worklists</h2><p>Turn stuck numbers into queues. PA, DSOH, leakage, cash, and doctor churn should become owner-driven work.</p></div><div class="action-list">${acts.map(a=>`<div class="action-item ${a.priority==='Critical'||a.priority==='High'?'red':a.priority==='Medium'?'amber':'green'}"><div class="action-title">${esc(a.title)} ${priorityBadge(a.priority)}</div><div class="action-copy">${esc(a.why)}</div></div>`).join('')}</div><h2>Script Age Funnel</h2>${funnel([['0-24 hours',Math.max(0,n(c.scriptsReceived)-n(c.paBacklog)),'good'],['24-48 hours',Math.round(n(c.paBacklog)*.3),'blue'],['48-72 hours',Math.round(n(c.paBacklog)*.4),'warn'],['72+ hours',Math.round(n(c.paBacklog)*.3),'bad']])}<h2>Retention Funnel</h2>${funnel([['First Fills',n(c.firstFills),'blue'],['Second Fills',n(c.secondFills),'good'],['DSOH Risk',n(c.dsOhRisk),'warn'],['Abandoned',n(c.scriptsAbandoned),'bad']])}`}

  function funnel(rows){let max=Math.max(...rows.map(r=>n(r[1])),1);return`<div class="funnel-card">${rows.map(([label,val,cls])=>`<div class="funnel-row"><div class="funnel-row-top"><span>${esc(label)}</span><span>${num(val)}</span></div><div class="funnel-bar"><div class="funnel-fill ${cls}" style="width:${Math.max(3,n(val)/max*100)}%"></div></div></div>`).join('')}</div>`}

  function renderDataQA(){let el=$('view-dataqa');if(!el)return;let c=safeCalc(),base={};try{base=JSON.parse(localStorage.getItem('opdash.pages.v1')||'{}')}catch(e){}let checks=[['Daily data saved',Object.keys(base.manual||{}).length>0],['Revenue is not negative',n(c.revenue)>=0],['COGS is not negative',n(c.cogs)>=0],['Scripts received >= filled',n(c.scriptsReceived)>=n(c.scriptsFilled)],['Cost/Rx calculated',n(c.costRx)>=0],['Backup reminder',true]];let rows=checks.map(([name,ok])=>[esc(name),ok?badge('Pass','good'):badge('Check','bad'),ok?'Looks okay':'Needs review']);el.innerHTML=`<div class="feature-hero"><h2>Data Quality</h2><p>Bad data makes good operators argue about the wrong numbers. Check the basics before the meeting.</p></div>${table(['Check','Status','Comment'],rows)}<h2>Import Discipline</h2><div class="action-list"><div class="action-item amber"><div class="action-title">Avoid double counting</div><div class="action-copy">Combined mode can double count if manual and imported data cover the same dates.</div></div><div class="action-item green"><div class="action-title">Save a backup weekly</div><div class="action-copy">Use Backup before major imports or after the weekly review.</div></div><div class="action-item amber"><div class="action-title">Normalize locations and channels</div><div class="action-copy">The same location spelled two ways becomes two locations.</div></div></div>`}

  function renderSecurity(){let s=state();if(s.settings.safetyAccepted)return;let app=$('appView');if(!app||$('safetyModal'))return;let modal=document.createElement('div');modal.id='safetyModal';modal.style.cssText='position:fixed;inset:0;background:rgba(15,23,42,.72);z-index:10000;display:grid;place-items:center;padding:18px';modal.innerHTML=`<div class="card" style="max-width:560px"><h2 style="margin-top:0">Data Safety Rule</h2><p class="muted">This is a public-code, local-browser dashboard. Use de-identified operating data only.</p><div class="action-list"><div class="action-item red"><div class="action-title">Do not enter PHI</div><div class="action-copy">No patient names, DOBs, addresses, phone numbers, or identifiable prescription details.</div></div><div class="action-item green"><div class="action-title">Use operating IDs and aggregates</div><div class="action-copy">Patient IDs, counts, locations, channels, drug classes, payer categories, and financial summaries are the right level.</div></div></div><button class="btn primary" onclick="OpsLayer.acceptSafety()">I understand</button></div>`;document.body.appendChild(modal)}

  function render(){ensureViews();ensureTabs();renderPeople();renderActions();renderBudget();renderPipeline();renderWorklists();renderDataQA();renderSecurity()}

  window.OpsLayer={render,show,acceptSafety(){let s=state();s.settings.safetyAccepted=true;save(s);$('safetyModal')?.remove()},addEmployee(){let s=state();s.employees.push({name:$('emp_name')?.value||'Unnamed',role:$('emp_role')?.value||'',team:$('emp_team')?.value||'',email:$('emp_email')?.value||'',tags:$('emp_tags')?.value||'',active:$('emp_active')?.value||'Yes'});save(s);toast('Employee added');render()},delEmployee(i){let s=state();s.employees.splice(i,1);save(s);render()},addAction(){let s=state();s.actions.push({title:$('act_title')?.value||'Action',owner:$('act_owner')?.value||'Unassigned',team:$('act_team')?.value||'',metric:$('act_metric')?.value||'',priority:$('act_priority')?.value||'Medium',due:$('act_due')?.value||today(),status:$('act_status')?.value||'Open',tags:$('act_tags')?.value||'',created:today()});save(s);toast('Action added');render()},acceptSuggestion(i){let a=suggestedActions()[i],s=state();s.actions.push({...a,owner:'Unassigned',status:'Open',due:today(),tags:a.metric,created:today()});save(s);toast('Suggested action created');render()},doneAction(i){let s=state();s.actions[i].status='Done';s.actions[i].closed=today();save(s);render()},delAction(i){let s=state();s.actions.splice(i,1);save(s);render()},addBudget(){let s=state();s.budgets.push({name:$('bud_name')?.value||'Budget',type:$('bud_type')?.value||'Location',period:$('bud_period')?.value||'',revenueBudget:$('bud_rev')?.value||0,gpBudget:$('bud_gp')?.value||0,opexBudget:$('bud_opex')?.value||0,scriptsBudget:$('bud_scripts')?.value||0});save(s);toast('Budget added');render()},delBudget(i){let s=state();s.budgets.splice(i,1);save(s);render()},addPipeline(){let s=state();s.pipeline.push({name:$('pipe_name')?.value||'Opportunity',type:$('pipe_type')?.value||'',stage:$('pipe_stage')?.value||'',expectedGp:$('pipe_gp')?.value||0,probability:$('pipe_prob')?.value||0,owner:$('pipe_owner')?.value||'Unassigned',nextStep:$('pipe_next')?.value||''});save(s);toast('Opportunity added');render()},delPipeline(i){let s=state();s.pipeline.splice(i,1);save(s);render()}};

  const originalRender=window.render;if(typeof originalRender==='function'){window.render=function(){let out=originalRender.apply(this,arguments);setTimeout(render,0);return out}}
  document.addEventListener('DOMContentLoaded',()=>setTimeout(render,700));
  setInterval(render,4000);
})();
