/* OnPoint Profiles Layer: location, doctor, enterprise, employee owner dashboards, monthly close, lender pack, pharmacist partner scorecard. */
(function(){
  'use strict';
  const BASE_KEY='opdash.pages.v1';
  const OPS_KEY='opdash.opslayer.v1';
  const PROFILE_KEY='opdash.profiles.v1';
  const $=id=>document.getElementById(id);
  const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const n=x=>Number(x)||0;
  const money=x=>'$'+Math.round(n(x)).toLocaleString();
  const num=x=>Math.round(n(x)).toLocaleString();
  const pct=x=>isFinite(x)?Number(x).toFixed(1)+'%':'0.0%';
  const today=()=>new Date().toISOString().slice(0,10);
  function base(){try{return JSON.parse(localStorage.getItem(BASE_KEY))||{manual:{},imports:{}}}catch(e){return{manual:{},imports:{}}}}
  function ops(){try{return JSON.parse(localStorage.getItem(OPS_KEY))||{employees:[],actions:[],pipeline:[],budgets:[]}}catch(e){return{employees:[],actions:[],pipeline:[],budgets:[]}}}
  function seed(){return{closeChecklist:defaultClose(),partnerRows:[],notes:{}}}
  function state(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY))||seed()}catch(e){return seed()}}
  function save(s){localStorage.setItem(PROFILE_KEY,JSON.stringify(s))}
  function safeCalc(){try{return typeof calc==='function'?calc():{}}catch(e){return{}}}
  function toast(msg){try{window.toast?window.toast(msg):alert(msg)}catch(e){}}
  function table(headers,rows){if(!rows.length)return`<div class="empty-state"><b>No data yet</b>Import PioneerRx / Power BI data or add rows to use this profile.</div>`;return`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function metric(label,value,sub='',cls=''){return`<div class="mini-card"><div class="label">${esc(label)}</div><div class="value ${cls}">${esc(value)}</div><div class="sub">${esc(sub)}</div></div>`}
  function badge(text,type){return`<span class="badge ${type||'blue'}">${esc(text)}</span>`}
  function input(id,val,left=false,type='text'){return`<input ${left?'class="left"':''} id="${esc(id)}" type="${type}" value="${esc(val??'')}">`}
  function select(id,opts,val){return`<select id="${esc(id)}">${opts.map(o=>`<option ${o===val?'selected':''}>${esc(o)}</option>`).join('')}</select>`}
  function download(name,text,type='text/plain'){const b=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click()}

  const tabs=[['locationprofiles','Location Profiles'],['doctorprofiles','Doctor Profiles'],['enterpriseprofiles','Account Profiles'],['ownerdash','Owner Dashboards'],['close','Monthly Close'],['capitalpack','Capital Pack'],['partnercard','Partner Scorecard']];
  function ensureViews(){const main=document.querySelector('.main');if(!main)return;tabs.forEach(([id])=>{if(!$('view-'+id)){const s=document.createElement('section');s.id='view-'+id;s.className='view';main.appendChild(s)}})}
  function ensureTabs(){const nav=$('nav');if(!nav)return;tabs.forEach(([id,label])=>{if(nav.querySelector(`[data-v="${id}"], [data-view="${id}"]`))return;const b=document.createElement('button');b.dataset.v=id;b.textContent=label;b.onclick=()=>show(id);nav.appendChild(b)})}
  function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-'+id)?.classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',(b.dataset.v||b.dataset.view)===id));const title=$('pageTitle');if(title)title.textContent=tabs.find(t=>t[0]===id)?.[1]||id;render();window.scrollTo({top:0,behavior:'smooth'})}

  function pioneer(){return((base().imports||{}).pioneer||[])}
  function powerbi(){return((base().imports||{}).powerbi||[])}
  function gp(r){return n(r.grossProfit)||n(r.gp)||n(r.revenue)-n(r.cogs)}
  function group(rows,fn){const g={};rows.forEach(r=>{const k=fn(r)||'Unknown';g[k]=g[k]||[];g[k].push(r)});return g}
  function sum(rows){const out={scripts:rows.length,revenue:0,cogs:0,gp:0,filled:0,abandoned:0,pa:0,adherence:[],time:[],patients:0};rows.forEach(r=>{out.revenue+=n(r.revenue);out.cogs+=n(r.cogs);out.gp+=gp(r);if(String(r.status||'').toLowerCase().includes('fill'))out.filled++;if(String(r.status||'').toLowerCase().includes('abandon'))out.abandoned++;if(r.paStatus)out.pa++;if(n(r.adherencePct))out.adherence.push(n(r.adherencePct));if(n(r.timeToStartHours))out.time.push(n(r.timeToStartHours));out.patients+=n(r.patients)});out.fillRate=out.scripts?out.filled/out.scripts*100:0;out.gpRx=out.scripts?out.gp/out.scripts:0;out.adherenceAvg=avg(out.adherence);out.timeAvg=avg(out.time);return out}
  function avg(a){return a.length?a.reduce((x,y)=>x+n(y),0)/a.length:0}

  function renderLocationProfiles(){const el=$('view-locationprofiles');if(!el)return;const by=group(pioneer(),r=>r.location||'Unknown');const rows=Object.entries(by).map(([k,rs])=>{const s=sum(rs);const score=Math.round(Math.min(100,s.gpRx+(s.fillRate/2)+(s.adherenceAvg/2)-s.abandoned*2));return[esc(k),num(s.scripts),money(s.revenue),money(s.gp),money(s.gpRx),pct(s.fillRate),pct(s.adherenceAvg),num(score),score>=75?badge('Strong','good'):score>=50?badge('Watch','warn'):badge('Fix','bad')]});el.innerHTML=`<div class="feature-hero"><h2>Location Profiles</h2><p>Each store needs a profile: volume, GP, fill rate, adherence, GP/Rx, and whether it deserves more capital, less cost, or a hard reset.</p></div><div class="kpi-band">${metric('Locations',num(rows.length),'with imported data')}${metric('Total Scripts',num(rows.reduce((a,r)=>a+Number(String(r[1]).replace(/,/g,'')),0)),'all locations')}${metric('Total GP',money(rows.reduce((a,r)=>a+Number(String(r[3]).replace(/[$,]/g,'')),0)),'all locations')}${metric('Strong Locations',num(rows.filter(r=>String(r[8]).includes('Strong')).length),'score >= 75')}${metric('Fix List',num(rows.filter(r=>String(r[8]).includes('Fix')).length),'score < 50')}</div>${table(['Location','Scripts','Revenue','GP','GP/Rx','Fill Rate','Adherence','Score','Status'],rows)}`}

  function renderDoctorProfiles(){const el=$('view-doctorprofiles');if(!el)return;const by=group(pioneer(),r=>r.doctor||'Unknown');const rows=Object.entries(by).map(([k,rs])=>{const s=sum(rs);const tier=s.gp>10000&&s.gpRx>=40?'A':s.gp>3000?'B':'C';const risk=s.scripts<3?'Thin relationship':s.abandoned>2?'Leakage':s.gpRx<20?'Low margin':'OK';return[esc(k),badge('Tier '+tier,tier==='A'?'good':tier==='B'?'warn':'bad'),num(s.scripts),money(s.gp),money(s.gpRx),pct(s.fillRate),num(s.pa),esc(risk)]}).sort((a,b)=>Number(String(b[3]).replace(/[$,]/g,''))-Number(String(a[3]).replace(/[$,]/g,'')));el.innerHTML=`<div class="feature-hero"><h2>Doctor Profiles</h2><p>Doctors are not just referral sources. They are operating relationships with volume, quality, margin, retention, and churn risk.</p></div>${table(['Doctor','Tier','Scripts','GP','GP/Rx','Fill Rate','PA Items','Risk'],rows)}`}

  function renderEnterpriseProfiles(){const el=$('view-enterpriseprofiles');if(!el)return;const rows=powerbi();const by=group(rows,r=>r.enterpriseAccount||r.account||'Unknown');const out=Object.entries(by).map(([k,rs])=>{const s=sum(rs);const patients=rs.reduce((a,r)=>a+n(r.patients),0);const received=rs.reduce((a,r)=>a+n(r.scriptsReceived),0);const filled=rs.reduce((a,r)=>a+n(r.scriptsFilled),0);return[esc(k),num(patients),num(received),num(filled),money(s.revenue),money(s.gp),money(filled?s.gp/filled:0),pct(received?filled/received*100:0),pct(s.adherenceAvg)]});el.innerHTML=`<div class="feature-hero"><h2>Enterprise Account Profiles</h2><p>Medical groups, pharma, payors, and strategic customers need account scorecards that prove access, therapy starts, persistence, and lower friction.</p></div>${table(['Account','Patients','Scripts Received','Scripts Filled','Revenue','GP','GP/Rx','Fill Rate','Adherence'],out)}<h2>Partner-Facing Language</h2><div class="card"><p class="muted">Use this page to create de-identified partner updates: patients served, scripts started, therapy delays reduced, adherence risk identified, and open issues.</p></div>`}

  function renderOwnerDash(){const el=$('view-ownerdash');if(!el)return;const o=ops();const employees=o.employees||[];const actions=o.actions||[];const rows=employees.map(e=>{const mine=actions.filter(a=>a.owner===e.name&&a.status!=='Done');const high=mine.filter(a=>a.priority==='Critical'||a.priority==='High').length;const blocked=mine.filter(a=>a.status==='Blocked').length;const due=mine.filter(a=>(a.due||'')<=today()).length;return[esc(e.name),esc(e.role),esc(e.team),num(mine.length),num(high),num(blocked),num(due),mine.length>6?badge('Overloaded','bad'):high?badge('Urgent','warn'):badge('OK','good')]});el.innerHTML=`<div class="feature-hero"><h2>Employee Owner Dashboards</h2><p>Every action needs an owner. This view shows who has work, who is overloaded, and where accountability is vague.</p></div>${table(['Employee','Role','Team','Open','High/Critical','Blocked','Due/Overdue','Status'],rows)}`}

  function defaultClose(){return[
    {item:'Bank transactions exported and imported',owner:'Finance',done:false},{item:'Sage Intacct P&L exported and imported',owner:'Finance',done:false},{item:'AP aging reviewed',owner:'Finance',done:false},{item:'AR / PBM receivables reviewed',owner:'Finance',done:false},{item:'Location contribution reviewed',owner:'Finance',done:false},{item:'Payroll and labor by location reviewed',owner:'Finance',done:false},{item:'Inventory / COGS sanity check complete',owner:'Finance',done:false},{item:'Debt and vendor payment plan updated',owner:'Finance',done:false},{item:'Budget vs actual reviewed',owner:'Executive',done:false},{item:'Leadership meeting report exported',owner:'Executive',done:false}
  ]}
  function renderClose(){const el=$('view-close');if(!el)return;const s=state();const done=s.closeChecklist.filter(x=>x.done).length;const rows=s.closeChecklist.map((x,i)=>[x.done?badge('Done','good'):badge('Open','warn'),esc(x.item),esc(x.owner),`<button class="btn" onclick="ProfilesLayer.toggleClose(${i})">Toggle</button>`]);el.innerHTML=`<div class="feature-hero"><h2>Monthly Close Checklist</h2><p>Make finance boring. Every month should close with the same checklist, the same files, and the same truth.</p></div><div class="kpi-band">${metric('Checklist Items',num(s.closeChecklist.length),'monthly tasks')}${metric('Completed',num(done),'done')}${metric('Open',num(s.closeChecklist.length-done),'remaining')}${metric('Progress',pct(s.closeChecklist.length?done/s.closeChecklist.length*100:0),'close completion')}${metric('Owner','Finance','default')}</div>${table(['Status','Item','Owner',''],rows)}<button class="btn blue" onclick="ProfilesLayer.resetClose()">Reset Month</button>`}

  function renderCapitalPack(){const el=$('view-capitalpack');if(!el)return;const c=safeCalc(),o=ops();const weighted=(o.pipeline||[]).reduce((a,r)=>a+n(r.expectedGp)*n(r.probability)/100,0);el.innerHTML=`<div class="feature-hero"><h2>Lender / Investor Reporting Pack</h2><p>A clean operating snapshot for lenders, investors, board members, and serious capital conversations.</p></div><div class="kpi-band">${metric('Revenue',money(c.revenue),'selected period')}${metric('Gross Profit',money(c.gp),'selected period')}${metric('EBITDA Proxy',money(c.ebitda),'selected period')}${metric('Weighted Pipeline',money(weighted),'future GP')}${metric('Cash',money(c.cash),'current')}</div><div class="card" id="capitalPack"><h2 style="margin-top:0">OnPoint Operating Snapshot</h2><p><b>Core thesis:</b> OnPoint gets patients started on therapy and keeps them on therapy faster, more consistently, more conveniently, and more cost-effectively.</p><p><b>Current period:</b> Revenue ${money(c.revenue)}, GP ${money(c.gp)}, GP/Rx ${money(c.gpRx)}, Cost/Rx ${money(c.costRx)}, Fill Rate ${pct(c.fill||c.fillRate)}.</p><p><b>Liquidity:</b> Cash ${money(c.cash)}, AP ${money(c.ap)}, Debt ${money(c.debt)}.</p><p><b>Operating risks:</b> PA backlog ${num(c.paBacklog)}, DSOH risk ${num(c.dsOhRisk)}, open actions ${(o.actions||[]).filter(a=>a.status!=='Done').length}.</p></div><button class="btn primary" onclick="ProfilesLayer.printCapitalPack()">Print / Save PDF</button> <button class="btn blue" onclick="ProfilesLayer.copyCapitalPack()">Copy Text</button>`}

  function renderPartnerCard(){const el=$('view-partnercard');if(!el)return;const c=safeCalc();el.innerHTML=`<div class="feature-hero"><h2>Pharmacist Partner Scorecard</h2><p>For the future partner-owned model: make the pharmacist-owner accountable for GP, service, adherence, cost, and operating discipline.</p></div><div class="kpi-band">${metric('Scripts Filled',num(c.scriptsFilled),'output')}${metric('GP',money(c.gp),'value captured')}${metric('GP/Rx',money(c.gpRx),'quality')}${metric('Cost/Rx',money(c.costRx),'discipline')}${metric('Adherence',pct(c.adherence),'patient continuity')}</div><h2>Partner Score Formula</h2>${table(['Area','Metric','Weight','Why It Matters'],[['Growth','Scripts filled / active patients','20%','Partner must grow the right volume'],['Profit','GP and GP/Rx','30%','Volume without margin is noise'],['Execution','Fill rate and time to therapy','20%','Patients need therapy started fast'],['Retention','Adherence / DSOH risk','20%','The product is staying on therapy'],['Discipline','Cost/Rx and action closure','10%','Ownership means cost control']])}`}

  async function copyText(text){await navigator.clipboard.writeText(text);toast('Copied')}
  function printHtml(id,title){const html=$(id)?.innerHTML||'';const w=window.open('','_blank');w.document.write('<html><head><title>'+esc(title)+'</title><style>body{font-family:Arial;padding:24px;line-height:1.45}</style></head><body>'+html+'</body></html>');w.document.close();w.print()}

  function render(){ensureViews();ensureTabs();renderLocationProfiles();renderDoctorProfiles();renderEnterpriseProfiles();renderOwnerDash();renderClose();renderCapitalPack();renderPartnerCard()}
  window.ProfilesLayer={render,show,toggleClose(i){const s=state();s.closeChecklist[i].done=!s.closeChecklist[i].done;save(s);render()},resetClose(){const s=state();s.closeChecklist=s.closeChecklist.map(x=>({...x,done:false}));save(s);render()},printCapitalPack(){printHtml('capitalPack','OnPoint Capital Pack')},copyCapitalPack(){const c=safeCalc();copyText(`OnPoint Operating Snapshot\nRevenue: ${money(c.revenue)}\nGross Profit: ${money(c.gp)}\nGP/Rx: ${money(c.gpRx)}\nCost/Rx: ${money(c.costRx)}\nFill Rate: ${pct(c.fill||c.fillRate)}\nCash: ${money(c.cash)}\nPA Backlog: ${num(c.paBacklog)}\nDSOH Risk: ${num(c.dsOhRisk)}`)}};
  const old=window.render;if(typeof old==='function'){window.render=function(){const out=old.apply(this,arguments);setTimeout(render,0);return out}}
  document.addEventListener('DOMContentLoaded',()=>setTimeout(render,1500));
  setInterval(render,7000);
})();
